namespace GhostDeck;

/// <summary>Prosta lokalizacja. Kolejnosc jezykow = indeksy w tablicach.</summary>
public static class Lang
{
    // indeks: 0 en, 1 pl, 2 de, 3 fr, 4 es, 5 zh, 6 pt, 7 ru
    public static readonly string[] Codes = { "en", "pl", "de", "fr", "es", "zh", "pt", "ru" };
    public static readonly string[] Names = { "English", "Polski", "Deutsch", "Français", "Español", "中文", "Português (BR)", "Русский" };

    private static int _idx = 0;

    public static string CurrentCode => Codes[_idx];

    public static void Set(string code)
    {
        int i = Array.IndexOf(Codes, code);
        _idx = i >= 0 ? i : 0;
    }

    public static string T(string key)
    {
        if (Map.TryGetValue(key, out var arr))
            return _idx < arr.Length && !string.IsNullOrEmpty(arr[_idx]) ? arr[_idx] : arr[0];
        return key;
    }

    private static readonly Dictionary<string, string[]> Map = new()
    {
        // ---- sub-tabs ----
        ["subtab_profiles"] = new[] { "Profiles", "Profile", "Profile", "Profils", "Perfiles", "配置文件", "Perfis", "Профили" },
        ["subtab_curve"]    = new[] { "Fan curve", "Krzywa wentylatora", "Lüfterkurve", "Courbe du ventilateur", "Curva del ventilador", "风扇曲线", "Curva da ventoinha", "Кривая вентилятора" },
        ["st_sub_charts"]   = new[] { "Charts", "Wykresy", "Diagramme", "Graphiques", "Gráficos", "图表", "Gráficos", "Графики" },
        ["st_sub_bytes"]    = new[] { "EC bytes", "Bajty EC", "EC-Bytes", "Octets EC", "Bytes EC", "EC 字节", "Bytes EC", "Байты EC" },
        ["st_sub_log"]      = new[] { "Change log", "Historia zmian", "Änderungen", "Journal", "Registro", "更改记录", "Alterações", "Журнал" },

        // ---- report: fan-curve verification flow ----
        ["rep_curve_intro"]   = new[]
        {
            "Help verify the fan-curve addresses for your model. Set the exact test curve below in MSI Center, then capture — we read it back from the EC (read-only) and locate it, then prepare a GitHub report.",
            "Pomóż zweryfikować adresy krzywej wentylatora dla Twojego modelu. Ustaw w MSI Center dokładnie poniższą krzywą testową, potem kliknij Zbierz — odczytamy ją z EC (tylko odczyt), zlokalizujemy i przygotujemy zgłoszenie na GitHub.",
            "Hilf, die Lüfterkurven-Adressen für dein Modell zu verifizieren. Stelle in MSI Center genau die untenstehende Testkurve ein, dann erfasse — wir lesen sie aus dem EC zurück (nur Lesen), lokalisieren sie und erstellen einen GitHub-Bericht.",
            "Aidez à vérifier les adresses de la courbe de ventilation pour votre modèle. Réglez exactement la courbe de test ci-dessous dans MSI Center, puis capturez — nous la relisons depuis l'EC (lecture seule), la localisons et préparons un rapport GitHub.",
            "Ayuda a verificar las direcciones de la curva del ventilador de tu modelo. Configura en MSI Center exactamente la curva de prueba de abajo y luego captura — la leemos del EC (solo lectura), la localizamos y preparamos un informe de GitHub.",
            "帮助验证你机型的风扇曲线地址。在 MSI Center 中精确设置下面的测试曲线，然后采集——我们会从 EC 读回（只读）并定位它，随后生成 GitHub 报告。",
            "Ajude a verificar os endereços da curva da ventoinha do seu modelo. Defina no MSI Center exatamente a curva de teste abaixo e capture — lemos de volta do EC (somente leitura), localizamos e preparamos um relatório no GitHub.",
            "Помогите проверить адреса кривой вентилятора для вашей модели. Задайте в MSI Center точно указанную ниже тестовую кривую, затем снимите — мы считаем её из EC (только чтение), найдём и подготовим отчёт на GitHub."
        },
        ["rep_curve_warn"] = new[]
        {
            "MSI Center only lets you edit the fan curve in Extreme Performance. Switch to that profile first.",
            "MSI Center pozwala edytować krzywą tylko w trybie Extreme Performance. Najpierw przełącz się na ten profil.",
            "MSI Center erlaubt das Bearbeiten der Lüfterkurve nur im Modus Extreme Performance. Wechsle zuerst zu diesem Profil.",
            "MSI Center ne permet de modifier la courbe qu'en mode Extreme Performance. Passez d'abord à ce profil.",
            "MSI Center solo permite editar la curva en modo Extreme Performance. Cambia primero a ese perfil.",
            "MSI Center 仅允许在 Extreme Performance 模式下编辑风扇曲线。请先切换到该配置文件。",
            "O MSI Center só permite editar a curva no modo Extreme Performance. Mude primeiro para esse perfil.",
            "MSI Center позволяет редактировать кривую только в режиме Extreme Performance. Сначала переключитесь на этот профиль."
        },
        ["rep_curve_steps"] = new[] { "STEPS", "KROKI", "SCHRITTE", "ÉTAPES", "PASOS", "步骤", "PASSOS", "ШАГИ" },
        ["rep_curve_why"] = new[]
        {
            "The values are deliberately unusual, so we can find exactly where MSI Center wrote them in the EC and confirm the curve addresses for your model.",
            "Wartości są celowo nietypowe, żebyśmy mogli znaleźć dokładnie tam, gdzie MSI Center zapisał je w EC, i potwierdzić adresy krzywej dla Twojego modelu.",
            "Die Werte sind bewusst ungewöhnlich, damit wir genau finden, wohin MSI Center sie im EC geschrieben hat, und die Kurvenadressen für dein Modell bestätigen können.",
            "Les valeurs sont volontairement inhabituelles, afin de trouver exactement où MSI Center les a écrites dans l'EC et de confirmer les adresses de la courbe pour votre modèle.",
            "Los valores son deliberadamente inusuales para poder encontrar exactamente dónde los escribió MSI Center en el EC y confirmar las direcciones de la curva de tu modelo.",
            "这些数值刻意与众不同，便于我们准确找到 MSI Center 在 EC 中写入的位置，并确认你机型的曲线地址。",
            "Os valores são propositalmente incomuns, para encontrarmos exatamente onde o MSI Center os gravou no EC e confirmar os endereços da curva do seu modelo.",
            "Значения намеренно необычные, чтобы мы могли точно найти, куда MSI Center записал их в EC, и подтвердить адреса кривой для вашей модели."
        },
        ["rep_curve_s1"] = new[]
        {
            "Switch the laptop to the Extreme Performance profile (Features → Extreme Performance).",
            "Przełącz laptop na profil Extreme Performance (Features → Extreme Performance).",
            "Wechsle das Notebook in das Profil Extreme Performance (Features → Extreme Performance).",
            "Passez le PC au profil Extreme Performance (Features → Extreme Performance).",
            "Cambia el portátil al perfil Extreme Performance (Features → Extreme Performance).",
            "将笔记本切换到 Extreme Performance 配置文件（Features → Extreme Performance）。",
            "Mude o notebook para o perfil Extreme Performance (Features → Extreme Performance).",
            "Переключите ноутбук в профиль Extreme Performance (Features → Extreme Performance)."
        },
        ["rep_curve_s2"] = new[]
        {
            "Open Advanced (the gear icon) → the Fan Speed tab → Advanced mode.",
            "Otwórz Advanced (koło zębate) → zakładka Fan Speed → tryb Advanced.",
            "Öffne Advanced (Zahnrad) → Reiter Fan Speed → Modus Advanced.",
            "Ouvrez Advanced (l'engrenage) → onglet Fan Speed → mode Advanced.",
            "Abre Advanced (el engranaje) → pestaña Fan Speed → modo Advanced.",
            "打开 Advanced（齿轮图标）→ Fan Speed 选项卡 → Advanced 模式。",
            "Abra Advanced (a engrenagem) → aba Fan Speed → modo Advanced.",
            "Откройте Advanced (шестерёнка) → вкладка Fan Speed → режим Advanced."
        },
        ["rep_curve_s3"] = new[]
        {
            "Set Fan 1 (CPU) to these values, in order: 25, 35, 45, 55, 65, 75 %.",
            "Ustaw wentylator 1 (CPU) na kolejne wartości: 25, 35, 45, 55, 65, 75 %.",
            "Stelle Lüfter 1 (CPU) der Reihe nach auf: 25, 35, 45, 55, 65, 75 %.",
            "Réglez le ventilateur 1 (CPU) sur, dans l'ordre : 25, 35, 45, 55, 65, 75 %.",
            "Ajusta el ventilador 1 (CPU) a, en orden: 25, 35, 45, 55, 65, 75 %.",
            "将风扇 1（CPU）依次设为：25、35、45、55、65、75 %。",
            "Defina o ventilador 1 (CPU), em ordem: 25, 35, 45, 55, 65, 75 %.",
            "Задайте вентилятор 1 (CPU) по порядку: 25, 35, 45, 55, 65, 75 %."
        },
        ["rep_curve_s4"] = new[]
        {
            "Set Fan 2 (GPU) to these values, in order: 20, 30, 40, 50, 60, 70 %.",
            "Ustaw wentylator 2 (GPU) na kolejne wartości: 20, 30, 40, 50, 60, 70 %.",
            "Stelle Lüfter 2 (GPU) der Reihe nach auf: 20, 30, 40, 50, 60, 70 %.",
            "Réglez le ventilateur 2 (GPU) sur, dans l'ordre : 20, 30, 40, 50, 60, 70 %.",
            "Ajusta el ventilador 2 (GPU) a, en orden: 20, 30, 40, 50, 60, 70 %.",
            "将风扇 2（GPU）依次设为：20、30、40、50、60、70 %。",
            "Defina o ventilador 2 (GPU), em ordem: 20, 30, 40, 50, 60, 70 %.",
            "Задайте вентилятор 2 (GPU) по порядку: 20, 30, 40, 50, 60, 70 %."
        },
        ["rep_curve_s5"] = new[]
        {
            "Click Save in MSI Center, come back here and press “Capture & scan”.",
            "Kliknij Save w MSI Center, wróć tutaj i naciśnij „Zbierz i skanuj”.",
            "Klicke in MSI Center auf Save, komm hierher zurück und drücke „Erfassen und scannen“.",
            "Cliquez sur Save dans MSI Center, revenez ici et appuyez sur « Capturer et analyser ».",
            "Haz clic en Save en MSI Center, vuelve aquí y pulsa «Capturar y escanear».",
            "在 MSI Center 点击 Save，返回此处并点击“采集并扫描”。",
            "Clique em Save no MSI Center, volte aqui e pressione “Capturar e analisar”.",
            "Нажмите Save в MSI Center, вернитесь сюда и нажмите «Снять и просканировать»."
        },
        ["rep_curve_capture"] = new[] { "Capture & scan", "Zbierz i skanuj", "Erfassen und scannen", "Capturer et analyser", "Capturar y escanear", "采集并扫描", "Capturar e analisar", "Снять и просканировать" },
        ["rep_curve_finish"]  = new[] { "Open GitHub report", "Otwórz zgłoszenie GitHub", "GitHub-Bericht öffnen", "Ouvrir le rapport GitHub", "Abrir informe de GitHub", "打开 GitHub 报告", "Abrir relatório no GitHub", "Открыть отчёт на GitHub" },
        ["rep_curve_found"]   = new[]
        {
            "Test curve found — CPU @ 0x{0:X2}, GPU @ 0x{1:X2}.", "Znaleziono krzywą testową — CPU @ 0x{0:X2}, GPU @ 0x{1:X2}.",
            "Testkurve gefunden — CPU @ 0x{0:X2}, GPU @ 0x{1:X2}.", "Courbe de test trouvée — CPU @ 0x{0:X2}, GPU @ 0x{1:X2}.",
            "Curva de prueba encontrada — CPU @ 0x{0:X2}, GPU @ 0x{1:X2}.", "已找到测试曲线 — CPU @ 0x{0:X2}，GPU @ 0x{1:X2}。",
            "Curva de teste encontrada — CPU @ 0x{0:X2}, GPU @ 0x{1:X2}.", "Тестовая кривая найдена — CPU @ 0x{0:X2}, GPU @ 0x{1:X2}."
        },
        ["rep_curve_match"]   = new[]
        {
            "Matches the shipped map — this model's curve can be marked verified.", "Zgodne z mapą w aplikacji — krzywą tego modelu można oznaczyć jako zweryfikowaną.",
            "Stimmt mit der mitgelieferten Zuordnung überein — die Kurve dieses Modells kann als verifiziert markiert werden.", "Correspond à la carte fournie — la courbe de ce modèle peut être marquée comme vérifiée.",
            "Coincide con el mapa incluido — la curva de este modelo puede marcarse como verificada.", "与内置映射一致——该机型的曲线可标记为已验证。",
            "Corresponde ao mapa incluído — a curva deste modelo pode ser marcada como verificada.", "Совпадает со встроенной картой — кривую этой модели можно отметить как проверенную."
        },
        ["rep_curve_nomatch"] = new[]
        {
            "Differs from the shipped map — sending the addresses for review.", "Różni się od mapy w aplikacji — wysyłam adresy do przeglądu.",
            "Weicht von der mitgelieferten Zuordnung ab — Adressen werden zur Prüfung gesendet.", "Diffère de la carte fournie — envoi des adresses pour examen.",
            "Difiere del mapa incluido — enviando las direcciones para revisión.", "与内置映射不同——正在发送地址以供审核。",
            "Difere do mapa incluído — enviando os endereços para revisão.", "Отличается от встроенной карты — отправляю адреса на проверку."
        },
        ["rep_curve_notfound"]= new[]
        {
            "Couldn't locate the test curve. Send the dump anyway so we can map it (did you Save in MSI Center?).", "Nie udało się znaleźć krzywej testowej. Wyślij zrzut mimo to (czy na pewno kliknięto Save w MSI Center?).",
            "Testkurve nicht gefunden. Sende den Dump trotzdem, damit wir sie zuordnen können (in MSI Center gespeichert?).", "Impossible de localiser la courbe de test. Envoyez quand même le vidage pour qu'on la cartographie (avez-vous cliqué sur Save dans MSI Center ?).",
            "No se pudo localizar la curva de prueba. Envía el volcado de todos modos para mapearla (¿guardaste en MSI Center?).", "未能定位测试曲线。仍请发送转储以便我们映射（是否在 MSI Center 点击了 Save？）。",
            "Não foi possível localizar a curva de teste. Envie o despejo mesmo assim para mapearmos (você clicou em Save no MSI Center?).", "Не удалось найти тестовую кривую. Всё равно отправьте дамп, чтобы мы её сопоставили (нажали Save в MSI Center?)."
        },
        ["rep_curve_notadvanced"]= new[]
        {
            "The Advanced fan curve isn't active right now — your laptop is in another profile, so the EC still holds the default curve. Switch to Extreme Performance, set the Advanced curve in MSI Center, click Save, and stay in Extreme, then capture again.",
            "Zaawansowana krzywa nie jest teraz aktywna — laptop jest w innym profilu, więc w EC jest wciąż domyślna krzywa. Przełącz na Extreme Performance, ustaw krzywą (Advanced) w MSI Center, kliknij Save i zostań w Extreme, potem przechwyć ponownie.",
            "Die erweiterte Lüfterkurve ist gerade nicht aktiv — dein Notebook ist in einem anderen Profil, daher enthält der EC noch die Standardkurve. Wechsle zu Extreme Performance, stelle die Advanced-Kurve in MSI Center ein, klicke Save, bleib in Extreme und erfasse erneut.",
            "La courbe avancée n'est pas active actuellement — votre PC est sur un autre profil, donc l'EC contient encore la courbe par défaut. Passez en Extreme Performance, réglez la courbe (Advanced) dans MSI Center, cliquez sur Save, restez en Extreme, puis capturez à nouveau.",
            "La curva avanzada no está activa ahora — tu portátil está en otro perfil, así que el EC aún tiene la curva por defecto. Cambia a Extreme Performance, configura la curva (Advanced) en MSI Center, haz clic en Save, quédate en Extreme y captura de nuevo.",
            "高级风扇曲线当前未激活——你的笔记本处于其他配置文件，因此 EC 中仍是默认曲线。请切换到 Extreme Performance，在 MSI Center 设置 Advanced 曲线，点击 Save 并保持在 Extreme，然后重新采集。",
            "A curva avançada não está ativa agora — seu notebook está em outro perfil, então o EC ainda tem a curva padrão. Mude para Extreme Performance, defina a curva (Advanced) no MSI Center, clique em Save, permaneça no Extreme e capture novamente.",
            "Расширенная кривая сейчас не активна — ноутбук в другом профиле, поэтому в EC всё ещё стандартная кривая. Переключитесь на Extreme Performance, задайте кривую (Advanced) в MSI Center, нажмите Save, оставайтесь в Extreme и снимите ещё раз."
        },

        // ---- Models: verify CTA ----
        ["models_verify_desc"]  = new[]
        {
            "Experimental models work but aren't hardware-confirmed. A 2-minute read-only capture lets us promote your model to Tested.",
            "Modele eksperymentalne działają, ale nie są potwierdzone sprzętowo. 2-minutowy odczyt (bez zapisu) pozwala awansować Twój model do Tested.",
            "Experimentelle Modelle funktionieren, sind aber nicht per Hardware bestätigt. Eine 2-minütige Nur-Lesen-Erfassung befördert dein Modell zu „Getestet“.",
            "Les modèles expérimentaux fonctionnent mais ne sont pas confirmés matériellement. Une capture en lecture seule de 2 min permet de faire passer votre modèle en « Testé ».",
            "Los modelos experimentales funcionan pero no están confirmados por hardware. Una captura de solo lectura de 2 minutos permite promover tu modelo a Probado.",
            "实验性机型可用，但未经硬件确认。2 分钟的只读采集即可将你的机型提升为“已测试”。",
            "Modelos experimentais funcionam, mas não são confirmados por hardware. Uma captura somente-leitura de 2 minutos permite promover seu modelo para Testado.",
            "Экспериментальные модели работают, но не подтверждены на железе. Двухминутное снятие (только чтение) позволит повысить вашу модель до «Проверено»."
        },
        ["models_verify_btn"]   = new[] { "Verify my model", "Zweryfikuj mój model", "Modell verifizieren", "Vérifier mon modèle", "Verificar mi modelo", "验证我的机型", "Verificar meu modelo", "Проверить мою модель" },

        // ---- Fan curve: report button ----
        ["fc_report_curve"] = new[] { "Report fan curve", "Zgłoś krzywą", "Lüfterkurve melden", "Signaler la courbe", "Reportar la curva", "报告风扇曲线", "Reportar a curva", "Сообщить о кривой" },

        // ---- tray: grouped report submenu ----
        ["tray_report"]       = new[] { "Report / verify", "Zgłoś / zweryfikuj", "Melden / verifizieren", "Signaler / vérifier", "Reportar / verificar", "报告 / 验证", "Reportar / verificar", "Сообщить / проверить" },
        ["tray_report_model"] = new[] { "My model…", "Mój model…", "Mein Modell…", "Mon modèle…", "Mi modelo…", "我的机型…", "Meu modelo…", "Моя модель…" },
        ["tray_report_curve"] = new[] { "Fan curve…", "Krzywą wentylatora…", "Lüfterkurve…", "Courbe du ventilateur…", "Curva del ventilador…", "风扇曲线…", "Curva da ventoinha…", "Кривая вентилятора…" },

        ["menu_settings"]  = new[] { "Settings", "Ustawienia", "Einstellungen", "Paramètres", "Configuración", "设置", "Configurações", "Настройки" },
        ["menu_status"]    = new[] { "Status", "Status", "Status", "Statut", "Estado", "状态", "Status", "Состояние" },
        ["menu_panel"]     = new[] { "Open panel", "Otwórz panel", "Panel öffnen", "Ouvrir le panneau", "Abrir panel", "打开面板", "Abrir painel", "Открыть панель" },

        // ---- Fan Boost (max fans) — generic name; the MSI "Cooler Boost" trademark is only referenced once, in the README ----
        ["cooler_boost"]     = new[] { "Fan Boost (max fans)", "Fan Boost (maks. wentylatory)", "Fan Boost (max. Lüfter)", "Fan Boost (ventilo max)", "Fan Boost (ventiladores máx.)", "Fan Boost（风扇全速）", "Fan Boost (ventoinhas máx.)", "Fan Boost (макс. вентиляторы)" },
        ["cooler_boost_on"]  = new[] { "Max fans ON", "Maks. obroty WŁ.", "Max. Lüfter EIN", "Ventilo max ACTIVÉ", "Ventiladores máx. ACT.", "风扇全速 开", "Ventoinhas máx. LIG.", "Макс. обороты ВКЛ" },
        ["cooler_boost_off"] = new[] { "Max fans off", "Maks. obroty WYŁ.", "Max. Lüfter AUS", "Ventilo max désactivé", "Ventiladores máx. des.", "风扇全速 关", "Ventoinhas máx. DESL.", "Макс. обороты ВЫКЛ" },
        ["cooler_boost_hint"]= new[] { "Force full fan speed regardless of profile. When turned off, the fans spin down gradually (can take 10–25 s).", "Wymuś pełne obroty wentylatorów niezależnie od profilu. Po wyłączeniu wentylatory zwalniają stopniowo (może to potrwać 10–25 s).", "Volle Lüfterdrehzahl unabhängig vom Profil erzwingen. Nach dem Ausschalten drehen die Lüfter allmählich herunter (kann 10–25 s dauern).", "Forcer la vitesse max des ventilateurs quel que soit le profil. À l'arrêt, les ventilateurs ralentissent progressivement (10–25 s).", "Forzar ventiladores al máximo sin importar el perfil. Al desactivar, bajan de forma gradual (puede tardar 10–25 s).", "无视配置文件强制风扇全速。关闭后风扇会逐渐降速（约 10–25 秒）。", "Forçar ventoinhas no máximo independentemente do perfil. Ao desligar, desaceleram gradualmente (pode levar 10–25 s).", "Принудительно макс. обороты независимо от профиля. При выключении вентиляторы снижают обороты постепенно (10–25 с)." },
        ["cooler_boost_short"]= new[] { "Fan Boost", "Fan Boost", "Fan Boost", "Fan Boost", "Fan Boost", "Fan Boost", "Fan Boost", "Fan Boost" },
        ["scen_features"]    = new[] { "Features", "Funkcje", "Funktionen", "Fonctions", "Funciones", "功能", "Funções", "Функции" },

        // ---- gaming overlay ----
        ["overlay_title"]    = new[] { "Gaming overlay", "Nakładka do gier", "Gaming-Overlay", "Overlay de jeu", "Overlay de juego", "游戏悬浮窗", "Overlay de jogo", "Игровой оверлей" },
        ["overlay_hint"]     = new[] { "Detachable always-on-top mini panel with temps, fan RPM and profile — for gaming. Drag to move; toggle with the hotkey. Options in Settings.", "Odczepiany, zawsze-na-wierzchu mini panel z temperaturami, obrotami i profilem — do grania. Przeciągnij, by przesunąć; przełącz skrótem. Opcje w Ustawieniach.", "Abnehmbares Mini-Panel (immer im Vordergrund) mit Temperaturen, Lüfter-RPM und Profil — fürs Gaming. Zum Verschieben ziehen; per Hotkey umschalten. Optionen in den Einstellungen.", "Mini-panneau détachable toujours au premier plan (températures, RPM, profil) — pour le jeu. Glisser pour déplacer ; raccourci pour afficher. Options dans les Réglages.", "Mini panel desacoplable siempre visible con temperaturas, RPM y perfil — para juegos. Arrastra para mover; alterna con el atajo. Opciones en Ajustes.", "可拆卸的置顶小面板，显示温度、风扇转速和配置文件——为游戏而生。拖动移动；快捷键切换。选项在设置中。", "Mini-painel destacável sempre no topo com temperaturas, RPM e perfil — para jogos. Arraste para mover; alterne com o atalho. Opções nas Definições.", "Открепляемая мини-панель поверх окон: температуры, обороты, профиль — для игр. Перетаскивайте мышью; переключение горячей клавишей. Настройки в разделе Настройки." },
        ["set_grp_overlay"]  = new[] { "Gaming overlay", "Nakładka do gier", "Gaming-Overlay", "Overlay de jeu", "Overlay de juego", "游戏悬浮窗", "Overlay de jogo", "Игровой оверлей" },
        ["ov_show"]          = new[] { "Show overlay", "Pokaż nakładkę", "Overlay anzeigen", "Afficher l'overlay", "Mostrar overlay", "显示悬浮窗", "Mostrar overlay", "Показать оверлей" },
        ["ov_layout"]        = new[] { "Layout", "Układ", "Layout", "Disposition", "Diseño", "布局", "Layout", "Вид" },
        ["ov_layout_card"]   = new[] { "Card", "Karta", "Karte", "Carte", "Tarjeta", "卡片", "Cartão", "Карта" },
        ["ov_layout_bar"]    = new[] { "Bar", "Pasek", "Leiste", "Barre", "Barra", "条形", "Barra", "Панель" },
        ["ov_opacity"]       = new[] { "Content opacity", "Przezroczystość treści", "Deckkraft Inhalt", "Opacité du contenu", "Opacidad contenido", "内容不透明度", "Opacidade do conteúdo", "Прозрачность содержимого" },
        ["ov_bg_opacity"]    = new[] { "Background opacity", "Przezroczystość tła", "Deckkraft Hintergrund", "Opacité du fond", "Opacidad de fondo", "背景不透明度", "Opacidade do fundo", "Прозрачность фона" },
        ["ov_scale"]         = new[] { "Size", "Rozmiar", "Größe", "Taille", "Tamaño", "大小", "Tamanho", "Размер" },
        ["ov_clickthrough"]  = new[] { "Lock position (click-through, can't drag)", "Zablokuj pozycję (klik-through, bez przeciągania)", "Position sperren (klick-durchlässig, kein Ziehen)", "Verrouiller (clic traversant, non déplaçable)", "Bloquear posición (clic pasante, sin arrastrar)", "锁定位置（点击穿透，不可拖动）", "Bloquear posição (clique-através, sem arrastar)", "Заблокировать (сквозные клики, без перетаскивания)" },
        ["ov_lock_menu"]     = new[] { "Lock overlay position", "Zablokuj pozycję nakładki", "Overlay-Position sperren", "Verrouiller l'overlay", "Bloquear posición del overlay", "锁定悬浮窗位置", "Bloquear posição do overlay", "Заблокировать оверлей" },
        ["ov_locked"]        = new[] { "Locked · click-through", "Zablokowana · klik-through", "Gesperrt · klick-durchlässig", "Verrouillé · clic traversant", "Bloqueado · clic pasante", "已锁定 · 点击穿透", "Bloqueado · clique-através", "Заблокирована · сквозные клики" },
        ["ov_unlocked"]      = new[] { "Unlocked · drag to move", "Odblokowana · przeciągnij", "Entsperrt · zum Verschieben ziehen", "Déverrouillé · glisser pour déplacer", "Desbloqueado · arrastra para mover", "已解锁 · 拖动移动", "Desbloqueado · arraste para mover", "Разблокирована · перетащите" },
        ["ov_ontop"]         = new[] { "Always on top", "Zawsze na wierzchu", "Immer im Vordergrund", "Toujours au premier plan", "Siempre visible", "总在最前", "Sempre no topo", "Поверх всех окон" },
        ["ov_accent"]        = new[] { "Accent = profile colour", "Akcent = kolor profilu", "Akzent = Profilfarbe", "Accent = couleur du profil", "Acento = color del perfil", "强调色 = 配置文件颜色", "Destaque = cor do perfil", "Акцент = цвет профиля" },
        ["ov_bold"]          = new[] { "Bold text", "Pogrubiony tekst", "Fetter Text", "Texte en gras", "Texto en negrita", "粗体文字", "Texto em negrito", "Жирный текст" },
        ["ov_metrics"]       = new[] { "What to show", "Co pokazywać", "Was anzeigen", "Quoi afficher", "Qué mostrar", "显示内容", "O que mostrar", "Что показывать" },
        ["ov_position"]      = new[] { "Position", "Pozycja", "Position", "Position", "Posición", "位置", "Posição", "Позиция" },
        ["ov_options"]       = new[] { "Options", "Opcje", "Optionen", "Options", "Opciones", "选项", "Opções", "Опции" },
        ["ov_hotkey"]        = new[] { "Shortcut — show/hide", "Skrót — pokaż/ukryj", "Kürzel — ein/aus", "Raccourci — afficher/masquer", "Atajo — mostrar/ocultar", "快捷键 — 显示/隐藏", "Atalho — mostrar/ocultar", "Клавиша — показать/скрыть" },
        ["ov_drag_hint"]     = new[] { "or drag with the mouse", "lub przeciągnij myszą", "oder mit der Maus ziehen", "ou glisser à la souris", "o arrastra con el ratón", "或用鼠标拖动", "ou arraste com o rato", "или перетащите мышью" },
        ["ov_pos_pick"]      = new[] { "Corners…", "Rogi…", "Ecken…", "Coins…", "Esquinas…", "边角…", "Cantos…", "Углы…" },
        ["ov_pos_tl"]        = new[] { "↖ Top-left", "↖ Lewy górny", "↖ Oben links", "↖ Haut gauche", "↖ Sup. izq.", "↖ 左上", "↖ Sup. esq.", "↖ Сверху слева" },
        ["ov_pos_tr"]        = new[] { "↗ Top-right", "↗ Prawy górny", "↗ Oben rechts", "↗ Haut droite", "↗ Sup. der.", "↗ 右上", "↗ Sup. dir.", "↗ Сверху справа" },
        ["ov_pos_bl"]        = new[] { "↙ Bottom-left", "↙ Lewy dolny", "↙ Unten links", "↙ Bas gauche", "↙ Inf. izq.", "↙ 左下", "↙ Inf. esq.", "↙ Снизу слева" },
        ["ov_pos_br"]        = new[] { "↘ Bottom-right", "↘ Prawy dolny", "↘ Unten rechts", "↘ Bas droite", "↘ Inf. der.", "↘ 右下", "↘ Inf. dir.", "↘ Снизу справа" },
        ["ov_m_temp"]        = new[] { "CPU / GPU temp", "Temp. CPU / GPU", "CPU-/GPU-Temp.", "Temp. CPU / GPU", "Temp. CPU / GPU", "CPU / GPU 温度", "Temp. CPU / GPU", "Темп. CPU / GPU" },
        ["ov_m_rpm"]         = new[] { "Fan RPM", "Obroty (RPM)", "Lüfter-RPM", "RPM ventilos", "RPM ventilador", "风扇转速", "RPM ventoinha", "Обороты" },
        ["ov_m_fanpct"]      = new[] { "Fan %", "Wentylatory (%)", "Lüfter %", "Ventilo %", "Ventilador %", "风扇 %", "Ventoinha %", "Вентил. %" },
        ["ov_m_profile"]     = new[] { "Active profile", "Aktywny profil", "Aktives Profil", "Profil actif", "Perfil activo", "当前配置文件", "Perfil ativo", "Активный профиль" },
        ["ov_m_cooler"]      = new[] { "Fan Boost", "Fan Boost", "Fan Boost", "Fan Boost", "Fan Boost", "Fan Boost", "Fan Boost", "Fan Boost" },
        ["ov_m_load"]        = new[] { "CPU load", "Obciążenie CPU", "CPU-Last", "Charge CPU", "Carga CPU", "CPU 占用", "Carga CPU", "Загрузка CPU" },
        ["ov_m_ram"]         = new[] { "RAM", "RAM", "RAM", "RAM", "RAM", "内存", "RAM", "ОЗУ" },
        ["ov_m_gpuusage"]    = new[] { "GPU load", "Użycie GPU", "GPU-Last", "Charge GPU", "Carga GPU", "GPU 占用", "Carga GPU", "Загрузка GPU" },
        ["ov_m_vram"]        = new[] { "VRAM", "VRAM", "VRAM", "VRAM", "VRAM", "显存", "VRAM", "Видеопамять" },
        ["ov_m_cpuclock"]    = new[] { "CPU clock", "Zegar CPU", "CPU-Takt", "Fréq. CPU", "Reloj CPU", "CPU 频率", "Clock CPU", "Частота CPU" },
        ["ov_bg"]            = new[] { "Background", "Tło", "Hintergrund", "Arrière-plan", "Fondo", "背景", "Fundo", "Фон" },
        ["ov_bg_color"]      = new[] { "Background colour", "Kolor tła", "Hintergrundfarbe", "Couleur de fond", "Color de fondo", "背景颜色", "Cor de fundo", "Цвет фона" },
        ["ov_restore"]       = new[] { "Restore defaults", "Przywróć domyślne", "Standard wiederherstellen", "Réinitialiser", "Restaurar valores", "恢复默认", "Restaurar padrões", "Сбросить" },
        ["ov_m_charge"]      = new[] { "Charge limit", "Limit ładowania", "Ladelimit", "Limite de charge", "Límite de carga", "充电限制", "Limite de carga", "Лимит заряда" },
        ["ov_m_battery"]     = new[] { "Battery %", "Bateria %", "Akku %", "Batterie %", "Batería %", "电量 %", "Bateria %", "Батарея %" },
        ["ov_lock_row"]      = new[] { "Lock position", "Zablokuj pozycję", "Position sperren", "Verrouiller la position", "Bloquear posición", "锁定位置", "Bloquear posição", "Заблокировать позицию" },
        ["ov_note"]          = new[] { "Shows over borderless / windowed-fullscreen games. Exclusive fullscreen may hide it.", "Widoczna w grach borderless / windowed-fullscreen. Tryb exclusive fullscreen może ją ukryć.", "Sichtbar bei randlosen / Fenster-Vollbild-Spielen. Exklusives Vollbild kann es verdecken.", "Visible sur les jeux sans bordure / plein écran fenêtré. Le plein écran exclusif peut le masquer.", "Visible en juegos sin bordes / pantalla completa en ventana. La pantalla completa exclusiva puede ocultarlo.", "在无边框/窗口化全屏游戏中可见。独占全屏可能会隐藏它。", "Visível em jogos sem bordas / ecrã inteiro em janela. O ecrã inteiro exclusivo pode ocultá-lo.", "Виден в играх без рамки / оконный полноэкранный. Эксклюзивный полноэкранный может скрыть его." },

        // ---- history log ----
        ["menu_log"]         = new[] { "Change log", "Historia zmian", "Änderungsprotokoll", "Journal des changements", "Registro de cambios", "更改日志", "Registro de alterações", "Журнал изменений" },
        ["log_title"]        = new[] { "Change history", "Historia zmian", "Änderungsverlauf", "Historique des changements", "Historial de cambios", "更改历史", "Histórico de alterações", "История изменений" },
        ["log_recent"]       = new[] { "Recent changes", "Ostatnie zmiany", "Letzte Änderungen", "Changements récents", "Cambios recientes", "最近更改", "Alterações recentes", "Недавние изменения" },
        ["log_full"]         = new[] { "Full log…", "Pełny log…", "Vollständiges Protokoll…", "Journal complet…", "Registro completo…", "完整日志…", "Registro completo…", "Полный журнал…" },
        ["log_empty"]        = new[] { "No changes recorded yet", "Brak zapisanych zmian", "Noch keine Änderungen", "Aucun changement enregistré", "Sin cambios registrados", "尚无记录", "Nenhuma alteração registrada", "Изменений пока нет" },
        ["log_col_time"]     = new[] { "Time", "Czas", "Zeit", "Heure", "Hora", "时间", "Hora", "Время" },
        ["log_col_source"]   = new[] { "Source", "Źródło", "Quelle", "Source", "Origen", "来源", "Origem", "Источник" },
        ["log_col_detail"]   = new[] { "Written bytes", "Zapisane bajty", "Geschriebene Bytes", "Octets écrits", "Bytes escritos", "写入字节", "Bytes escritos", "Записанные байты" },
        ["log_col_result"]   = new[] { "Readback", "Odczyt", "Rücklesen", "Relecture", "Relectura", "回读", "Releitura", "Обратное чтение" },
        ["log_copy_all"]     = new[] { "Copy all", "Kopiuj wszystko", "Alles kopieren", "Tout copier", "Copiar todo", "全部复制", "Copiar tudo", "Копировать всё" },
        ["log_clear"]        = new[] { "Clear", "Wyczyść", "Löschen", "Effacer", "Borrar", "清除", "Limpar", "Очистить" },
        ["log_clear_confirm"]= new[] { "Clear the whole change history?", "Wyczyścić całą historię zmian?", "Gesamten Änderungsverlauf löschen?", "Effacer tout l'historique ?", "¿Borrar todo el historial?", "清除全部历史？", "Limpar todo o histórico?", "Очистить всю историю?" },
        ["log_read_fail"]    = new[] { "readback failed", "odczyt nieudany", "Rücklesen fehlgeschlagen", "relecture échouée", "relectura fallida", "回读失败", "releitura falhou", "ошибка чтения" },
        ["log_err"]          = new[] { "error", "błąd", "Fehler", "erreur", "error", "错误", "erro", "ошибка" },
        ["log_charge"]       = new[] { "Charge limit {0}%", "Limit ładowania {0}%", "Ladelimit {0}%", "Limite de charge {0}%", "Límite de carga {0}%", "充电限制 {0}%", "Limite de carga {0}%", "Лимит заряда {0}%" },
        ["log_external"]     = new[] { "External change: {0} → {1}", "Zmiana zewnętrzna: {0} → {1}", "Externe Änderung: {0} → {1}", "Changement externe : {0} → {1}", "Cambio externo: {0} → {1}", "外部更改：{0} → {1}", "Alteração externa: {0} → {1}", "Внешнее изменение: {0} → {1}" },
        ["log_curve_on"]     = new[] { "Custom fan curve ON", "Własna krzywa wentylatora WŁ.", "Eigene Lüfterkurve EIN", "Courbe perso ACTIVÉE", "Curva personalizada ACT.", "自定义风扇曲线 开", "Curva personalizada LIG.", "Своя кривая ВКЛ" },
        ["log_curve_off"]    = new[] { "Custom fan curve off", "Własna krzywa wentylatora WYŁ.", "Eigene Lüfterkurve AUS", "Courbe perso désactivée", "Curva personalizada des.", "自定义风扇曲线 关", "Curva personalizada DESL.", "Своя кривая ВЫКЛ" },

        // ---- log sources ----
        ["log_src_startup"]  = new[] { "startup", "start", "Start", "démarrage", "inicio", "启动", "início", "запуск" },
        ["log_src_hotkey"]   = new[] { "hotkey", "skrót", "Tastenkürzel", "raccourci", "atajo", "快捷键", "atalho", "гор. клавиша" },
        ["log_src_tray"]     = new[] { "tray", "zasobnik", "Infobereich", "barre d'état", "bandeja", "托盘", "bandeja", "трей" },
        ["log_src_panel"]    = new[] { "panel", "panel", "Panel", "panneau", "panel", "面板", "painel", "панель" },
        ["log_src_autoac"]   = new[] { "auto AC/battery", "auto AC/bateria", "Auto Netz/Akku", "auto secteur/batt.", "auto CA/batería", "自动 电源/电池", "auto CA/bateria", "авто сеть/батарея" },
        ["log_src_fancurve"] = new[] { "fan curve", "krzywa went.", "Lüfterkurve", "courbe ventilo", "curva vent.", "风扇曲线", "curva ventoinha", "кривая вент." },
        ["log_src_external"] = new[] { "external sync", "sync. zewn.", "externer Sync", "sync externe", "sinc. externa", "外部同步", "sinc. externa", "внешняя синхр." },
        ["log_src_charge"]   = new[] { "charge limit", "limit ładowania", "Ladelimit", "limite charge", "límite carga", "充电限制", "limite carga", "лимит заряда" },
        ["log_src_cooler"]   = new[] { "fan boost", "fan boost", "Fan Boost", "fan boost", "fan boost", "Fan Boost", "fan boost", "fan boost" },
        ["log_src_firmware"] = new[] { "firmware", "firmware", "Firmware", "firmware", "firmware", "固件", "firmware", "прошивка" },
        ["log_src_test"]     = new[] { "test tool", "narz. testowe", "Testtool", "outil de test", "herr. de prueba", "测试工具", "ferr. de teste", "тест. инстр." },

        // ---- firmware-change warning ----
        ["menu_fw_ack"]      = new[] { "⚠ Firmware changed — verify model", "⚠ Zmiana firmware — zweryfikuj model", "⚠ Firmware geändert — Modell prüfen", "⚠ Firmware modifié — vérifier le modèle", "⚠ Firmware cambiado — verificar modelo", "⚠ 固件已更改 — 请核对型号", "⚠ Firmware alterado — verificar modelo", "⚠ Прошивка изменена — проверьте модель" },
        ["fw_changed_title"] = new[] { "EC firmware changed", "Zmieniono firmware EC", "EC-Firmware geändert", "Firmware EC modifié", "Firmware EC cambiado", "EC 固件已更改", "Firmware EC alterado", "Прошивка EC изменена" },
        ["fw_changed_text"]  = new[] { "EC firmware changed — automatic writes are paused. Verify the model again, then click to acknowledge.", "Firmware EC uległ zmianie — automatyczne zapisy wstrzymane. Zweryfikuj model ponownie, potem kliknij, aby potwierdzić.", "EC-Firmware hat sich geändert — automatische Schreibvorgänge pausiert. Modell erneut prüfen und zum Bestätigen klicken.", "Le firmware EC a changé — écritures automatiques suspendues. Vérifiez le modèle puis cliquez pour confirmer.", "El firmware EC cambió — escrituras automáticas en pausa. Verifica el modelo y haz clic para confirmar.", "EC 固件已更改 — 自动写入已暂停。请重新核对型号后点击确认。", "O firmware EC mudou — gravações automáticas pausadas. Verifique o modelo e clique para confirmar.", "Прошивка EC изменилась — автозапись приостановлена. Проверьте модель и нажмите для подтверждения." },
        ["log_fw_changed"]   = new[] { "EC firmware changed: {0} → {1} (auto-writes blocked)", "Zmiana firmware EC: {0} → {1} (auto-zapisy zablokowane)", "EC-Firmware geändert: {0} → {1} (Auto-Schreiben blockiert)", "Firmware EC modifié : {0} → {1} (écritures auto bloquées)", "Firmware EC cambiado: {0} → {1} (escrituras auto bloqueadas)", "EC 固件已更改：{0} → {1}（自动写入已阻止）", "Firmware EC alterado: {0} → {1} (gravações auto bloqueadas)", "Прошивка EC изменена: {0} → {1} (автозапись заблокирована)" },
        ["log_fw_ack"]       = new[] { "Firmware change acknowledged", "Potwierdzono zmianę firmware", "Firmware-Änderung bestätigt", "Changement de firmware confirmé", "Cambio de firmware confirmado", "已确认固件更改", "Alteração de firmware confirmada", "Изменение прошивки подтверждено" },
        ["tab_scenarios"]  = new[] { "Scenarios", "Scenariusze", "Szenarien", "Scénarios", "Escenarios", "场景", "Cenários", "Сценарии" },
        ["tab_updates"]    = new[] { "Updates", "Aktualizacje", "Updates", "Mises à jour", "Actualizaciones", "更新", "Atualizações", "Обновления" },
        ["scen_title"]     = new[] { "Choose a scenario", "Wybierz scenariusz", "Szenario wählen", "Choisir un scénario", "Elige un escenario", "选择场景", "Escolha um cenário", "Выберите сценарий" },
        ["scen_autoswitch"]= new[] { "Auto-switch on AC / battery", "Auto-przełączanie AC / bateria", "Auto-Wechsel bei Netz / Akku", "Bascule auto secteur / batterie", "Cambio automático CA / batería", "接通/电池自动切换", "Troca automática CA / bateria", "Авто-переключение сеть / батарея" },
        ["gen_off"]        = new[] { "Off", "Wyłączone", "Aus", "Désactivé", "Apagado", "关闭", "Desligado", "Выкл" },
        ["gen_off_short"]  = new[] { "Off", "Wył.", "Aus", "Off", "No", "关", "Não", "Выкл" },
        ["upd_installed"]  = new[] { "Installed version", "Zainstalowana wersja", "Installierte Version", "Version installée", "Versión instalada", "已安装版本", "Versão instalada", "Установленная версия" },
        ["upd_latest_ok"]  = new[] { "You're on the latest version", "Używasz najnowszej wersji", "Sie nutzen die neueste Version", "Vous avez la dernière version", "Tienes la última versión", "已是最新版本", "Você está na versão mais recente", "У вас последняя версия" },
        ["upd_check_now"]  = new[] { "Check now", "Sprawdź teraz", "Jetzt prüfen", "Vérifier maintenant", "Comprobar ahora", "立即检查", "Verificar agora", "Проверить сейчас" },
        ["upd_checking"]   = new[] { "Checking…", "Sprawdzanie…", "Wird geprüft…", "Vérification…", "Comprobando…", "正在检查…", "Verificando…", "Проверка…" },
        ["upd_last_checked"] = new[] { "Last checked: {0}", "Ostatnio sprawdzano: {0}", "Zuletzt geprüft: {0}", "Dernière vérification : {0}", "Última comprobación: {0}", "上次检查：{0}", "Última verificação: {0}", "Последняя проверка: {0}" },
        ["upd_never"]      = new[] { "never", "nigdy", "nie", "jamais", "nunca", "从未", "nunca", "никогда" },
        ["upd_available"]  = new[] { "New version {0} is available", "Dostępna nowa wersja {0}", "Neue Version {0} verfügbar", "Nouvelle version {0} disponible", "Nueva versión {0} disponible", "有新版本 {0}", "Nova versão {0} disponível", "Доступна новая версия {0}" },
        ["upd_install"]    = new[] { "Install {0}", "Zainstaluj {0}", "{0} installieren", "Installer {0}", "Instalar {0}", "安装 {0}", "Instalar {0}", "Установить {0}" },
        ["upd_downloading"] = new[] { "Downloading… {0}%", "Pobieranie… {0}%", "Wird heruntergeladen… {0}%", "Téléchargement… {0}%", "Descargando… {0}%", "正在下载… {0}%", "Baixando… {0}%", "Загрузка… {0}%" },
        ["upd_restarting"] = new[] { "Restarting to finish the update…", "Ponowne uruchamianie, aby dokończyć aktualizację…", "Neustart zum Abschluss des Updates…", "Redémarrage pour terminer la mise à jour…", "Reiniciando para finalizar la actualización…", "正在重启以完成更新…", "Reiniciando para concluir a atualização…", "Перезапуск для завершения обновления…" },
        ["upd_dl_failed"]  = new[] { "Download failed — opening the releases page.", "Pobieranie nie powiodło się - otwieram stronę wydań.", "Download fehlgeschlagen — Release-Seite wird geöffnet.", "Échec du téléchargement — ouverture de la page des versions.", "Error de descarga — abriendo la página de versiones.", "下载失败 — 正在打开发布页面。", "Falha no download — abrindo a página de versões.", "Сбой загрузки — открываю страницу релизов." },
        ["upd_download"]   = new[] { "Download", "Pobierz", "Herunterladen", "Télécharger", "Descargar", "下载", "Baixar", "Скачать" },
        ["upd_history"]    = new[] { "Release history", "Historia wydań", "Versionsverlauf", "Historique des versions", "Historial de versiones", "发布历史", "Histórico de versões", "История версий" },
        ["upd_details"]    = new[] { "Details", "Szczegóły", "Details", "Détails", "Detalles", "详情", "Detalhes", "Подробности" },
        ["upd_offline"]    = new[] { "Couldn't reach GitHub. Check your connection and try again.", "Nie udało się połączyć z GitHub. Sprawdź połączenie i spróbuj ponownie.", "GitHub nicht erreichbar. Verbindung prüfen und erneut versuchen.", "Impossible de joindre GitHub. Vérifiez la connexion et réessayez.", "No se pudo conectar con GitHub. Revisa la conexión e inténtalo de nuevo.", "无法连接 GitHub。请检查网络后重试。", "Não foi possível acessar o GitHub. Verifique a conexão e tente novamente.", "Не удалось подключиться к GitHub. Проверьте соединение и повторите." },
        ["set_advanced"]   = new[] { "Advanced settings (colours, hotkeys)…", "Ustawienia zaawansowane (kolory, skróty)…", "Erweiterte Einstellungen (Farben, Tastenkürzel)…", "Paramètres avancés (couleurs, raccourcis)…", "Ajustes avanzados (colores, atajos)…", "高级设置（颜色、快捷键）…", "Configurações avançadas (cores, atalhos)…", "Расширенные настройки (цвета, горячие клавиши)…" },
        ["set_theme"]      = new[] { "Theme", "Motyw", "Design", "Thème", "Tema", "主题", "Tema", "Тема" },
        ["set_theme_light"]= new[] { "Light", "Jasny", "Hell", "Clair", "Claro", "浅色", "Claro", "Светлая" },
        ["set_theme_dark"] = new[] { "Dark", "Ciemny", "Dunkel", "Sombre", "Oscuro", "深色", "Escuro", "Тёмная" },
        ["set_check_updates"] = new[] { "Check for updates automatically", "Sprawdzaj aktualizacje automatycznie", "Automatisch nach Updates suchen", "Vérifier les mises à jour automatiquement", "Buscar actualizaciones automáticamente", "自动检查更新", "Verificar atualizações automaticamente", "Автоматически проверять обновления" },
        ["menu_language"]  = new[] { "Language", "Język", "Sprache", "Langue", "Idioma", "语言", "Idioma", "Язык" },
        ["menu_exit"]      = new[] { "Exit", "Zamknij", "Beenden", "Quitter", "Salir", "退出", "Sair", "Выход" },

        ["set_hotkeys"]    = new[] { "Keyboard shortcuts", "Skróty klawiszowe", "Tastenkürzel", "Raccourcis clavier", "Atajos de teclado", "键盘快捷键", "Atalhos de teclado", "Горячие клавиши" },
        ["hk_all"]         = new[] { "All shortcuts", "Wszystkie skróty", "Alle Kürzel", "Tous les raccourcis", "Todos los atajos", "所有快捷键", "Todos os atalhos", "Все клавиши" },
        ["set_hint"]       = new[] { "Click a field and press a combo.  Esc / Delete = clear.", "Kliknij pole i wciśnij kombinację.  Esc / Delete = wyczyść.", "Feld anklicken und Kombination drücken.  Esc / Entf = löschen.", "Cliquez sur un champ et appuyez sur une combinaison.  Échap / Suppr = effacer.", "Haz clic en un campo y pulsa una combinación.  Esc / Supr = borrar.", "点击字段并按下组合键。Esc / Delete = 清除。", "Clique num campo e pressione uma combinação.  Esc / Delete = limpar.", "Нажмите поле и введите комбинацию.  Esc / Delete = очистить." },
        ["cycle"]          = new[] { "Cycle (next)", "Cykl (następny)", "Wechseln (nächstes)", "Cycle (suivant)", "Ciclo (siguiente)", "循环（下一个）", "Ciclo (próximo)", "Цикл (следующий)" },
        ["set_autostart"]  = new[] { "Start with Windows", "Uruchamiaj z Windowsem", "Mit Windows starten", "Démarrer avec Windows", "Iniciar con Windows", "随 Windows 启动", "Iniciar com o Windows", "Запускать с Windows" },
        ["set_default"]    = new[] { "Defaults", "Domyślne", "Standard", "Défaut", "Predeterminado", "默认", "Padrão", "По умолчанию" },
        ["set_save"]       = new[] { "Save", "Zapisz", "Speichern", "Enregistrer", "Guardar", "保存", "Salvar", "Сохранить" },
        ["set_close"]      = new[] { "Close", "Zamknij", "Schließen", "Fermer", "Cerrar", "关闭", "Fechar", "Закрыть" },
        ["set_saved"]      = new[] { "✓ Saved", "✓ Zapisano", "✓ Gespeichert", "✓ Enregistré", "✓ Guardado", "✓ 已保存", "✓ Salvo", "✓ Сохранено" },
        ["set_reset_hint"] = new[] { "Defaults restored (click Save).", "Przywrócono domyślne (kliknij Zapisz).", "Standard wiederhergestellt (Speichern).", "Valeurs par défaut (cliquez Enregistrer).", "Restaurado (haz clic en Guardar).", "已恢复默认（点击保存）。", "Padrões restaurados (clique em Salvar).", "Восстановлено (нажмите Сохранить)." },
        ["set_language"]   = new[] { "Language", "Język", "Sprache", "Langue", "Idioma", "语言", "Idioma", "Язык" },
        ["set_colors"]     = new[] { "Profile colors", "Kolory profili", "Profilfarben", "Couleurs des profils", "Colores de perfil", "配置文件颜色", "Cores dos perfis", "Цвета профилей" },
        ["set_colors_reset"] = new[] { "Restore default colors", "Przywróć domyślne kolory", "Standardfarben wiederherstellen", "Restaurer les couleurs par défaut", "Restaurar colores predeterminados", "恢复默认颜色", "Restaurar cores padrão", "Восстановить цвета по умолчанию" },
        ["set_charge"]     = new[] { "Battery charge limit", "Limit ładowania baterii", "Akkuladelimit", "Limite de charge batterie", "Límite de carga", "电池充电限制", "Limite de carga", "Лимит заряда батареи" },
        ["charge_dont"]    = new[] { "Don't change", "Nie zmieniaj", "Nicht ändern", "Ne pas changer", "No cambiar", "不更改", "Não alterar", "Не менять" },
        ["set_autoswitch"] = new[] { "Auto-switch AC / battery", "Auto-przełączanie zasilacz / bateria", "Auto-Wechsel Netz / Akku", "Bascule auto secteur / batterie", "Cambio auto CA / batería", "电源/电池自动切换", "Troca auto tomada / bateria", "Автопереключение сеть / батарея" },
        ["on_ac"]          = new[] { "On AC", "Na zasilaczu", "Am Netz", "Sur secteur", "Con CA", "接通电源", "Na tomada", "От сети" },
        ["on_battery"]     = new[] { "On battery", "Na baterii", "Im Akku", "Sur batterie", "Con batería", "使用电池", "Na bateria", "От батареи" },

        ["status_title"]   = new[] { "Status / Diagnostics", "Status / Diagnostyka", "Status / Diagnose", "Statut / Diagnostic", "Estado / Diagnóstico", "状态 / 诊断", "Status / Diagnóstico", "Состояние / Диагностика" },
        ["st_profile"]     = new[] { "Active profile", "Aktywny profil", "Aktives Profil", "Profil actif", "Perfil activo", "当前配置", "Perfil ativo", "Активный профиль" },
        ["st_cpu_temp"]    = new[] { "CPU temperature", "Temperatura CPU", "CPU-Temperatur", "Température CPU", "Temperatura CPU", "CPU 温度", "Temperatura da CPU", "Температура ЦП" },
        ["st_gpu_temp"]    = new[] { "GPU temperature", "Temperatura GPU", "GPU-Temperatur", "Température GPU", "Temperatura GPU", "GPU 温度", "Temperatura da GPU", "Температура ГП" },
        ["st_cpu_fan"]     = new[] { "CPU fan", "Wentylator CPU", "CPU-Lüfter", "Ventilateur CPU", "Ventilador CPU", "CPU 风扇", "Ventilador da CPU", "Вентилятор ЦП" },
        ["st_gpu_fan"]     = new[] { "GPU fan", "Wentylator GPU", "GPU-Lüfter", "Ventilateur GPU", "Ventilador GPU", "GPU 风扇", "Ventilador da GPU", "Вентилятор ГП" },
        ["st_charge"]      = new[] { "Charge limit", "Limit ładowania", "Ladelimit", "Limite de charge", "Límite de carga", "充电限制", "Limite de carga", "Лимит заряда" },
        ["st_firmware"]    = new[] { "EC firmware", "Firmware EC", "EC-Firmware", "Firmware EC", "Firmware EC", "EC 固件", "Firmware EC", "Прошивка EC" },
        ["st_switches"]    = new[] { "Switches (session)", "Przełączeń (sesja)", "Wechsel (Sitzung)", "Changements (session)", "Cambios (sesión)", "切换次数（本次）", "Trocas (sessão)", "Переключений (сессия)" },
        ["st_in_profile"]  = new[] { "Time in profile", "Czas w profilu", "Zeit im Profil", "Temps dans le profil", "Tiempo en perfil", "当前配置时长", "Tempo no perfil", "Время в профиле" },
        ["st_autostart"]   = new[] { "Autostart", "Autostart", "Autostart", "Démarrage auto", "Inicio automático", "自动启动", "Início automático", "Автозапуск" },
        ["st_app_ver"]     = new[] { "App version", "Wersja aplikacji", "App-Version", "Version de l'app", "Versión de la app", "应用版本", "Versão do app", "Версия приложения" },
        ["st_cpu_clock"]   = new[] { "CPU clock (approx.)", "Zegar CPU (przybl.)", "CPU-Takt (ca.)", "Fréq. CPU (approx.)", "Reloj CPU (aprox.)", "CPU 频率(约)", "Clock CPU (aprox.)", "Частота CPU (прибл.)" },
        ["st_gpu_usage"]   = new[] { "GPU load", "Użycie GPU", "GPU-Last", "Charge GPU", "Carga GPU", "GPU 占用", "Carga GPU", "Загрузка GPU" },
        ["st_vram"]        = new[] { "VRAM used", "Użycie VRAM", "VRAM belegt", "VRAM utilisée", "VRAM usada", "显存占用", "VRAM usada", "Видеопамять" },
        ["st_battery"]     = new[] { "Battery", "Bateria", "Akku", "Batterie", "Batería", "电量", "Bateria", "Батарея" },
        ["st_refresh"]     = new[] { "Refresh", "Odśwież", "Aktualisieren", "Actualiser", "Actualizar", "刷新", "Atualizar", "Обновить" },
        ["always_on_top"]  = new[] { "Always on top", "Zawsze na wierzchu", "Immer im Vordergrund", "Toujours au-dessus", "Siempre visible", "总在最前", "Sempre no topo", "Поверх всех окон" },
        ["st_model"]       = new[] { "Model", "Model", "Modell", "Modèle", "Modelo", "型号", "Modelo", "Модель" },
        ["unsupported_title"] = new[] { "Unsupported model", "Niewspierany model", "Nicht unterstütztes Modell", "Modèle non pris en charge", "Modelo no compatible", "不支持的型号", "Modelo não suportado", "Модель не поддерживается" },
        ["unsupported_sub"]   = new[] { "read-only — contribute on GitHub", "tylko odczyt — zgłoś model na GitHub", "schreibgeschützt — auf GitHub beitragen", "lecture seule — contribuez sur GitHub", "solo lectura — contribuye en GitHub", "只读 — 在 GitHub 上贡献", "somente leitura — contribua no GitHub", "только чтение — добавьте на GitHub" },
        ["experimental_enable"] = new[] { "Enable experimental models (unverified)", "Włącz modele eksperymentalne (niezweryfikowane)", "Experimentelle Modelle aktivieren (ungeprüft)", "Activer les modèles expérimentaux (non vérifiés)", "Activar modelos experimentales (no verificados)", "启用实验性型号（未验证）", "Ativar modelos experimentais (não verificados)", "Включить экспериментальные модели (непроверенные)" },
        ["set_check_updates"] = new[] {
            "Check for updates (once a day)", "Sprawdzaj aktualizacje (raz dziennie)", "Auf Updates prüfen (täglich)",
            "Vérifier les mises à jour (une fois par jour)", "Buscar actualizaciones (una vez al día)",
            "检查更新（每天一次）", "Procurar atualizações (uma vez por dia)", "Проверять обновления (раз в день)" },
        ["update_available"] = new[] {
            "Update available", "Dostępna aktualizacja", "Update verfügbar", "Mise à jour disponible",
            "Actualización disponible", "有可用更新", "Atualização disponível", "Доступно обновление" },
        ["update_available_text"] = new[] {
            "Version {0} is available — click to download.", "Dostępna jest wersja {0} — kliknij, aby pobrać.",
            "Version {0} ist verfügbar – zum Herunterladen klicken.", "La version {0} est disponible — cliquez pour télécharger.",
            "La versión {0} está disponible — haz clic para descargar.", "新版本 {0} 可用 — 点击下载。",
            "A versão {0} está disponível — clique para baixar.", "Доступна версия {0} — нажмите, чтобы скачать." },
        ["menu_update"] = new[] {
            "⬇ Download new version", "⬇ Pobierz nową wersję", "⬇ Neue Version herunterladen",
            "⬇ Télécharger la nouvelle version", "⬇ Descargar nueva versión", "⬇ 下载新版本",
            "⬇ Baixar nova versão", "⬇ Скачать новую версию" },
        ["experimental_locked"] = new[] { "experimental — enable in Settings", "eksperymentalny — włącz w Ustawieniach", "experimentell — in Einstellungen aktivieren", "expérimental — activez dans Paramètres", "experimental — actívalo en Ajustes", "实验性 — 在设置中启用", "experimental — ative nas Configurações", "экспериментально — включите в настройках" },
        ["tier_experimental"]   = new[] { "experimental", "eksperymentalny", "experimentell", "expérimental", "experimental", "实验性", "experimental", "экспериментальный" },
        ["tier_tested"]         = new[] { "tested", "zweryfikowany", "getestet", "testé", "probado", "已测试", "testado", "проверено" },
        ["tier_unsupported"]    = new[] { "unsupported", "niewspierany", "nicht unterstützt", "non pris en charge", "no compatible", "不支持", "não suportado", "не поддерживается" },

        // ---- Report my model wizard ----
        ["menu_report"]    = new[] { "Report my model…", "Zgłoś mój model…", "Mein Modell melden…", "Signaler mon modèle…", "Reportar mi modelo…", "上报我的型号…", "Relatar meu modelo…", "Сообщить о модели…" },
        ["menu_feedback"]  = new[] { "Send feedback…", "Wyślij opinię…", "Feedback senden…", "Envoyer un avis…", "Enviar comentarios…", "发送反馈…", "Enviar feedback…", "Отправить отзыв…" },
        ["notice_more"]    = new[] { "Details", "Szczegóły", "Details", "Détails", "Detalles", "详情", "Detalhes", "Подробнее" },
        ["rep_title"]      = new[] { "Report my model", "Zgłoś mój model", "Mein Modell melden", "Signaler mon modèle", "Reportar mi modelo", "上报我的型号", "Relatar meu modelo", "Сообщить о модели" },
        ["rep_intro"]      = new[] {
            "Help add support for your laptop. This reads your EC in each MSI Center scenario (READ-ONLY — nothing is written) and prepares a GitHub report for you.",
            "Pomóż dodać wsparcie dla Twojego laptopa. Odczytamy EC w każdym scenariuszu MSI Center (TYLKO ODCZYT — nic nie jest zapisywane) i przygotujemy zgłoszenie na GitHub.",
            "Hilf, Unterstützung für dein Gerät hinzuzufügen. Liest den EC in jedem MSI-Center-Szenario (NUR LESEN — nichts wird geschrieben) und erstellt einen GitHub-Bericht.",
            "Aidez à prendre en charge votre PC. Lit l'EC dans chaque scénario MSI Center (LECTURE SEULE — rien n'est écrit) et prépare un rapport GitHub.",
            "Ayuda a añadir soporte para tu portátil. Lee el EC en cada escenario de MSI Center (SOLO LECTURA — no se escribe nada) y prepara un informe de GitHub.",
            "帮助为你的笔记本添加支持。将在每个 MSI Center 场景下读取 EC（只读——不写入任何内容）并为你准备 GitHub 报告。",
            "Ajude a adicionar suporte ao seu notebook. Lê o EC em cada cenário do MSI Center (SOMENTE LEITURA — nada é gravado) e prepara um relatório no GitHub.",
            "Помогите добавить поддержку вашего ноутбука. Считывает EC в каждом сценарии MSI Center (ТОЛЬКО ЧТЕНИЕ — ничего не записывается) и готовит отчёт на GitHub." },
        ["rep_need_msi"]   = new[] {
            "Requires MSI Center installed (to set each scenario as a reference).",
            "Wymaga zainstalowanego MSI Center (do ustawienia każdego scenariusza jako wzorca).",
            "Erfordert installiertes MSI Center (zum Setzen jedes Szenarios als Referenz).",
            "Nécessite MSI Center installé (pour définir chaque scénario comme référence).",
            "Requiere MSI Center instalado (para fijar cada escenario como referencia).",
            "需要已安装 MSI Center（用于将每个场景设为参考）。",
            "Requer o MSI Center instalado (para definir cada cenário como referência).",
            "Требуется установленный MSI Center (чтобы задать каждый сценарий как эталон)." },
        ["rep_msi_tip"]    = new[] {
            "Best with MSI Center 2.0.48 — the last version with a working SILENT scenario. Newer versions auto-update and silently drop SILENT after a reboot (exactly why this app exists).",
            "Najlepiej mieć MSI Center 2.0.48 — ostatnią wersję z działającym scenariuszem SILENT. Nowsze wersje same się aktualizują i po restarcie tracą tryb SILENT (właśnie dlatego powstała ta aplikacja).",
            "Am besten mit MSI Center 2.0.48 — der letzten Version mit funktionierendem SILENT-Szenario. Neuere Versionen aktualisieren sich selbst und verlieren SILENT nach einem Neustart (genau deshalb gibt es diese App).",
            "De préférence MSI Center 2.0.48 — la dernière version avec un scénario SILENT fonctionnel. Les versions plus récentes se mettent à jour seules et perdent SILENT après un redémarrage (la raison d'être de cette app).",
            "Mejor con MSI Center 2.0.48 — la última versión con el escenario SILENT funcional. Las versiones nuevas se autoactualizan y pierden SILENT tras reiniciar (justo por eso existe esta app).",
            "最好使用 MSI Center 2.0.48——最后一个 SILENT 场景可用的版本。较新版本会自动更新，重启后悄悄失去 SILENT（这正是本应用存在的原因）。",
            "Melhor com o MSI Center 2.0.48 — a última versão com o cenário SILENT funcionando. Versões mais novas se atualizam sozinhas e perdem o SILENT após reiniciar (exatamente por isso este app existe).",
            "Лучше всего MSI Center 2.0.48 — последняя версия с рабочим сценарием SILENT. Новые версии сами обновляются и теряют SILENT после перезагрузки (именно поэтому появилось это приложение)." },
        ["rep_msi_clean"]  = new[] {
            "Before installing 2.0.48, fully remove the current MSI Center with MSI's official cleaner:",
            "Przed instalacją 2.0.48 usuń całkowicie obecny MSI Center oficjalnym narzędziem MSI:",
            "Vor der Installation von 2.0.48 das aktuelle MSI Center mit dem offiziellen MSI-Cleaner vollständig entfernen:",
            "Avant d'installer 2.0.48, supprimez complètement le MSI Center actuel avec l'outil officiel MSI :",
            "Antes de instalar 2.0.48, elimina por completo el MSI Center actual con la herramienta oficial de MSI:",
            "安装 2.0.48 之前，请用 MSI 官方清理工具彻底卸载当前的 MSI Center：",
            "Antes de instalar o 2.0.48, remova completamente o MSI Center atual com a ferramenta oficial da MSI:",
            "Перед установкой 2.0.48 полностью удалите текущий MSI Center официальной утилитой MSI:" },
        ["rep_msi_download"] = new[] {
            "Get MSI Center 2.0.48 from Uptodown. Use the direct link; if it ever stops working, use the full version list as a fallback:",
            "Pobierz MSI Center 2.0.48 z Uptodown. Użyj linku bezpośredniego; gdyby przestał działać, skorzystaj z pełnej listy wersji jako zapasowej:",
            "MSI Center 2.0.48 von Uptodown laden. Direktlink verwenden; falls er nicht mehr funktioniert, die vollständige Versionsliste als Ausweichoption nutzen:",
            "Téléchargez MSI Center 2.0.48 depuis Uptodown. Utilisez le lien direct ; s'il cesse de fonctionner, utilisez la liste complète des versions en secours :",
            "Descarga MSI Center 2.0.48 desde Uptodown. Usa el enlace directo; si deja de funcionar, usa la lista completa de versiones como alternativa:",
            "从 Uptodown 获取 MSI Center 2.0.48。请使用直链；若失效，可改用完整版本列表作为备用：",
            "Baixe o MSI Center 2.0.48 no Uptodown. Use o link direto; se parar de funcionar, use a lista completa de versões como alternativa:",
            "Скачайте MSI Center 2.0.48 с Uptodown. Используйте прямую ссылку; если она перестанет работать, используйте полный список версий как запасной вариант:" },
        ["rep_dl_version"] = new[] {
            "Download MSI Center 2.0.48 (direct link)",
            "Pobierz MSI Center 2.0.48 (link bezpośredni)",
            "MSI Center 2.0.48 herunterladen (Direktlink)",
            "Télécharger MSI Center 2.0.48 (lien direct)",
            "Descargar MSI Center 2.0.48 (enlace directo)",
            "下载 MSI Center 2.0.48（直链）",
            "Baixar MSI Center 2.0.48 (link direto)",
            "Скачать MSI Center 2.0.48 (прямая ссылка)" },
        ["rep_dl_repo"] = new[] {
            "All MSI Center versions on Uptodown (fallback)",
            "Wszystkie wersje MSI Center na Uptodown (zapasowo)",
            "Alle MSI-Center-Versionen auf Uptodown (Ausweich)",
            "Toutes les versions de MSI Center sur Uptodown (secours)",
            "Todas las versiones de MSI Center en Uptodown (alternativa)",
            "Uptodown 上的所有 MSI Center 版本（备用）",
            "Todas as versões do MSI Center no Uptodown (alternativa)",
            "Все версии MSI Center на Uptodown (запасной вариант)" },
        ["rep_uninstaller_link"] = new[] {
            "Download CleanCenterMaster (official MSI uninstaller)",
            "Pobierz CleanCenterMaster (oficjalny deinstalator MSI)",
            "CleanCenterMaster herunterladen (offizieller MSI-Deinstaller)",
            "Télécharger CleanCenterMaster (désinstalleur officiel MSI)",
            "Descargar CleanCenterMaster (desinstalador oficial de MSI)",
            "下载 CleanCenterMaster（MSI 官方卸载工具）",
            "Baixar CleanCenterMaster (desinstalador oficial da MSI)",
            "Скачать CleanCenterMaster (официальный деинсталлятор MSI)" },
        ["rep_section"]    = new[] { "EC CAPTURE", "PRZECHWYTYWANIE EC", "EC-ERFASSUNG", "CAPTURE EC", "CAPTURA EC", "EC 采集", "CAPTURA DO EC", "СНЯТИЕ EC" },
        ["st_cpu_usage"]   = new[] { "CPU usage", "Użycie CPU", "CPU-Last", "Charge CPU", "Uso de CPU", "CPU 占用", "Uso da CPU", "Загрузка CPU" },
        ["st_ram"]         = new[] { "RAM", "RAM", "RAM", "RAM", "RAM", "内存", "RAM", "ОЗУ" },
        ["test_tools"]     = new[] { "Test tools (advanced)", "Narzędzia testowe (zaawansowane)", "Testwerkzeuge (erweitert)", "Outils de test (avancé)", "Herramientas de prueba", "测试工具（高级）", "Ferramentas de teste", "Тест-инструменты" },
        ["test_title"]     = new[] { "Test tools", "Narzędzia testowe", "Testwerkzeuge", "Outils de test", "Herramientas de prueba", "测试工具", "Ferramentas de teste", "Тест-инструменты" },
        ["test_rpm_btn"]   = new[] { "Scan for fan RPM register", "Skanuj rejestr RPM wentylatora", "Lüfter-RPM-Register suchen", "Chercher le registre RPM", "Buscar registro RPM", "扫描风扇 RPM 寄存器", "Procurar registo de RPM", "Поиск регистра RPM" },
        ["test_rpm_hint"]  = new[] {
            "Read-only. Match a value below to the RPM shown in MSI Center, then tell me the address.",
            "Tylko odczyt. Dopasuj wartość poniżej do RPM z MSI Center i podaj mi adres.",
            "Nur Lesen. Ordne einen Wert dem RPM in MSI Center zu und nenne mir die Adresse.",
            "Lecture seule. Associez une valeur au RPM de MSI Center, puis donnez-moi l'adresse.",
            "Solo lectura. Asocia un valor al RPM de MSI Center y dime la dirección.",
            "只读。把下面的值与 MSI Center 的 RPM 对应，然后告诉我地址。",
            "Somente leitura. Associe um valor ao RPM do MSI Center e me diga o endereço.",
            "Только чтение. Сопоставьте значение с RPM в MSI Center и сообщите адрес." },
        ["test_rpm_a"]     = new[] { "Step 1: capture current speed", "Krok 1: zapisz obecne obroty", "Schritt 1: aktuelle Drehzahl", "Étape 1 : vitesse actuelle", "Paso 1: velocidad actual", "步骤 1：记录当前转速", "Passo 1: velocidade atual", "Шаг 1: текущие обороты" },
        ["test_rpm_b"]     = new[] { "Step 2: scan + compare", "Krok 2: skanuj i porównaj", "Schritt 2: scannen + vergleichen", "Étape 2 : scanner + comparer", "Paso 2: escanear y comparar", "步骤 2：扫描并比较", "Passo 2: escanear e comparar", "Шаг 2: сканировать и сравнить" },
        ["test_rpm_hint2"] = new[] {
            "Run step 1, then change fan speed (use the experiment below), then step 2. Addresses whose value changed are the tachometers — match to MSI Center.",
            "Zrób krok 1, potem zmień obroty (użyj eksperymentu poniżej), potem krok 2. Adresy, które się zmieniły, to tachometry — dopasuj do MSI Center.",
            "Schritt 1, dann Drehzahl ändern (Experiment unten), dann Schritt 2. Geänderte Adressen sind die Tachos — mit MSI Center abgleichen.",
            "Étape 1, changez la vitesse (expérience ci-dessous), puis étape 2. Les adresses modifiées sont les tachymètres — comparez à MSI Center.",
            "Paso 1, cambia la velocidad (experimento abajo), luego paso 2. Las direcciones que cambiaron son los tacómetros — compara con MSI Center.",
            "先步骤 1，改变转速（用下面的实验），再步骤 2。发生变化的地址就是转速寄存器——与 MSI Center 对照。",
            "Passo 1, mude a velocidade (experimento abaixo), depois passo 2. Os endereços que mudaram são os tacômetros — compare com o MSI Center.",
            "Шаг 1, измените обороты (эксперимент ниже), затем шаг 2. Изменившиеся адреса — это тахометры, сверьте с MSI Center." },
        ["test_dump_btn"]  = new[] { "Save EC dump to file", "Zapisz zrzut EC do pliku", "EC-Dump speichern", "Enregistrer le dump EC", "Guardar volcado EC", "保存 EC 转储到文件", "Salvar dump do EC", "Сохранить дамп EC" },
        ["test_live"]      = new[] { "Live RPM:", "RPM na żywo:", "Live-RPM:", "RPM en direct :", "RPM en vivo:", "实时转速：", "RPM ao vivo:", "Обороты вживую:" },
        ["tab_fancurve"]   = new[] { "Fan curve", "Krzywa wentylatora", "Lüfterkurve", "Courbe ventilateur", "Curva ventilador", "风扇曲线", "Curva da ventoinha", "Кривая вентилятора" },
        ["fc_title"]       = new[] { "Fan curve", "Krzywa wentylatora", "Lüfterkurve", "Courbe du ventilateur", "Curva del ventilador", "风扇曲线", "Curva da ventoinha", "Кривая вентилятора" },
        ["fc_hint"]        = new[] {
            "Drag the points up/down to set fan speed per temperature. Apply writes the curve and runs it in the current power mode.",
            "Przeciągaj punkty góra/dół, aby ustawić obroty dla danej temperatury. „Zastosuj” zapisuje krzywą i uruchamia ją w aktualnym trybie.",
            "Punkte hoch/runter ziehen, um die Drehzahl je Temperatur zu setzen. „Anwenden” nutzt die Kurve im aktuellen Modus.",
            "Glissez les points pour régler la vitesse par température. « Appliquer » utilise la courbe dans le mode actuel.",
            "Arrastra los puntos para fijar la velocidad por temperatura. «Aplicar» usa la curva en el modo actual.",
            "上下拖动各点以设置对应温度的转速。“应用”会在当前模式下使用该曲线。",
            "Arraste os pontos para definir a velocidade por temperatura. “Aplicar” usa a curva no modo atual.",
            "Перетаскивайте точки, чтобы задать обороты для температуры. «Применить» включает кривую в текущем режиме." },
        ["fc_locked"]      = new[] {
            "Editing is available only on supported (Tested / enabled experimental) models.",
            "Edycja dostępna tylko na obsługiwanych modelach (Tested / włączone eksperymentalne).",
            "Bearbeitung nur auf unterstützten Modellen (Tested / aktiviert experimentell).",
            "Édition disponible uniquement sur les modèles pris en charge (Tested / expérimental activé).",
            "La edición solo está disponible en modelos compatibles (Tested / experimental habilitado).",
            "仅支持的机型（Tested / 已启用实验性）可编辑。",
            "Edição disponível apenas em modelos suportados (Tested / experimental ativado).",
            "Редактирование доступно только на поддерживаемых моделях (Tested / включён эксперимент)." },
        ["fc_fan_cpu"]     = new[] { "Fan 1 (CPU)", "Wentylator 1 (CPU)", "Lüfter 1 (CPU)", "Ventilateur 1 (CPU)", "Ventilador 1 (CPU)", "风扇 1（CPU）", "Ventoinha 1 (CPU)", "Вентилятор 1 (CPU)" },
        ["fc_fan_gpu"]     = new[] { "Fan 2 (GPU)", "Wentylator 2 (GPU)", "Lüfter 2 (GPU)", "Ventilateur 2 (GPU)", "Ventilador 2 (GPU)", "风扇 2（GPU）", "Ventoinha 2 (GPU)", "Вентилятор 2 (GPU)" },
        ["fc_apply"]       = new[] { "Apply", "Zastosuj", "Anwenden", "Appliquer", "Aplicar", "应用", "Aplicar", "Применить" },
        ["fc_restore"]     = new[] { "Restore automatic fans", "Przywróć automatyczne", "Automatik wiederherstellen", "Rétablir l'automatique", "Restaurar automático", "恢复自动", "Restaurar automático", "Вернуть авто" },
        ["fc_enable"]      = new[] { "Custom fan curve (override this profile)", "Własna krzywa wentylatora (nadpisz ten profil)", "Eigene Lüfterkurve (Profil überschreiben)", "Courbe perso (remplacer ce profil)", "Curva personalizada (anular este perfil)", "自定义风扇曲线（覆盖此模式）", "Curva personalizada (substituir este perfil)", "Своя кривая (заменить профиль)" },
        ["st_matrix"]      = new[] { "Profile bytes (EC)", "Bajty profilu (EC)", "Profil-Bytes (EC)", "Octets de profil (EC)", "Bytes de perfil (EC)", "配置字节 (EC)", "Bytes do perfil (EC)", "Байты профиля (EC)" },
        ["st_now"]         = new[] { "Now (live)", "Teraz (na żywo)", "Jetzt (live)", "Maintenant", "Ahora", "当前（实时）", "Agora", "Сейчас" },
        ["st_b_byte"]      = new[] { "Byte", "Bajt", "Byte", "Octet", "Byte", "字节", "Byte", "Байт" },
        ["st_b_role"]      = new[] { "Controls", "Za co odpowiada", "Steuert", "Contrôle", "Controla", "作用", "Controla", "Отвечает за" },
        ["st_b_vals"]      = new[] { "Values", "Wartości", "Werte", "Valeurs", "Valores", "取值", "Valores", "Значения" },
        ["st_b_power"]     = new[] { "Power / performance", "Moc / wydajność", "Leistung", "Puissance", "Potencia", "性能", "Desempenho", "Мощность" },
        ["st_b_cap"]       = new[] { "Extreme power", "Moc Extreme", "Extreme-Leistung", "Puissance Extreme", "Potencia Extreme", "Extreme 功耗", "Potência Extreme", "Мощность Extreme" },
        ["st_b_others"]    = new[] { "others", "reszta", "andere", "autres", "resto", "其余", "outros", "остальные" },
        ["st_b_batt"]      = new[] { "Super battery", "Super-bateria", "Super-Akku", "Super batterie", "Súper batería", "超级省电", "Super bateria", "Супер-батарея" },
        ["st_b_fan"]       = new[] { "Fan", "Wentylator", "Lüfter", "Ventilateur", "Ventilador", "风扇", "Ventoinha", "Вентилятор" },
        ["st_curve_live"]  = new[] { "Fan curve tables (live)", "Tablice krzywej (na żywo)", "Lüfterkurven-Tabellen (live)", "Tables de courbe (live)", "Tablas de curva (vivo)", "风扇曲线表（实时）", "Tabelas da curva (ao vivo)", "Таблицы кривой (вживую)" },
        ["st_point"]       = new[] { "Point", "Punkt", "Punkt", "Point", "Punto", "点", "Ponto", "Точка" },
        ["st_fan_silent"]  = new[] { "silent", "cicho", "leise", "silencieux", "silencio", "静音", "silencioso", "тихо" },
        ["st_fan_auto"]    = new[] { "auto", "auto", "auto", "auto", "auto", "自动", "auto", "авто" },
        ["st_fan_curve"]   = new[] { "curve", "krzywa", "Kurve", "courbe", "curva", "曲线", "curva", "кривая" },
        ["st_v_comfort"]   = new[] { "comfort", "komfort", "Komfort", "confort", "confort", "舒适", "conforto", "комфорт" },
        ["st_v_turbo"]     = new[] { "turbo", "turbo", "Turbo", "turbo", "turbo", "极速", "turbo", "турбо" },
        ["st_v_eco"]       = new[] { "eco", "eco", "Eco", "éco", "eco", "节能", "eco", "эко" },
        ["st_on"]          = new[] { "on", "wł", "an", "activé", "act.", "开", "lig.", "вкл" },
        ["st_off"]         = new[] { "off", "wył", "aus", "désact.", "desact.", "关", "des.", "выкл" },
        ["fc_preview"]     = new[] {
            "Curve addresses are not verified on this model yet — check the preview matches MSI Center (Extreme → Advanced). You can revert any time.",
            "Adresy krzywej nie są jeszcze zweryfikowane na tym modelu — sprawdź, czy podgląd zgadza się z MSI Center (Extreme → Advanced). Możesz cofnąć w każdej chwili.",
            "Kurvenadressen für dieses Modell noch nicht geprüft — prüfe, ob die Vorschau MSI Center (Extreme → Advanced) entspricht. Jederzeit rückgängig.",
            "Adresses de courbe non vérifiées sur ce modèle — vérifiez que l'aperçu correspond à MSI Center (Extreme → Advanced). Réversible à tout moment.",
            "Direcciones de curva sin verificar en este modelo — comprueba que la vista coincide con MSI Center (Extreme → Advanced). Reversible.",
            "此型号的曲线地址尚未验证——请确认预览与 MSI Center（Extreme → Advanced）一致。可随时还原。",
            "Endereços da curva ainda não verificados neste modelo — confira se a prévia bate com o MSI Center (Extreme → Advanced). Reversível.",
            "Адреса кривой на этой модели не проверены — сверьте предпросмотр с MSI Center (Extreme → Advanced). Можно вернуть в любой момент." },
        ["st_matrix_note"] = new[] {
            "0x34 = Extreme power unlock (written 00 in Extreme, 01 elsewhere), but it reads dynamically and can show 00/01 in any comfort profile — so it is NOT used for detection. Silent vs Balanced is decided solely by the fan byte 0xD4 (1D = Silent).",
            "0x34 = odblokowanie mocy Extreme (zapisywane 00 w Extreme, 01 w pozostałych), ale odczytuje się dynamicznie i bywa 00/01 w każdym profilu komfort — dlatego NIE służy do detekcji. O Silent vs Balanced decyduje wyłącznie bajt wentylatora 0xD4 (1D = Silent).",
            "0x34 = Extreme-Leistungsfreigabe (00 in Extreme, sonst 01 geschrieben), liest sich aber dynamisch und kann in jedem Komfortprofil 00/01 zeigen — daher NICHT zur Erkennung. Silent vs Balanced entscheidet allein das Lüfterbyte 0xD4 (1D = Silent).",
            "0x34 = déblocage puissance Extreme (écrit 00 en Extreme, 01 ailleurs), mais sa lecture est dynamique et peut afficher 00/01 dans tout profil confort — donc PAS utilisé pour la détection. Silent vs Balanced dépend uniquement de l'octet 0xD4 (1D = Silent).",
            "0x34 = desbloqueo de potencia Extreme (se escribe 00 en Extreme, 01 en el resto), pero su lectura es dinámica y puede mostrar 00/01 en cualquier perfil confort — por eso NO se usa para detección. Silent vs Balanced lo decide solo el byte 0xD4 (1D = Silent).",
            "0x34 = Extreme 功耗解锁（Extreme 写 00，其余写 01），但读取是动态的，任何舒适档都可能显示 00/01——故不用于识别。Silent 与 Balanced 仅由风扇字节 0xD4 区分（1D = Silent）。",
            "0x34 = desbloqueio de potência Extreme (gravado 00 no Extreme, 01 nos outros), mas a leitura é dinâmica e pode mostrar 00/01 em qualquer perfil conforto — por isso NÃO é usado na detecção. Silent vs Balanced é decidido só pelo byte 0xD4 (1D = Silent).",
            "0x34 = разблокировка мощности Extreme (пишется 00 в Extreme, 01 в остальных), но читается динамически и может показывать 00/01 в любом комфортном профиле — поэтому НЕ используется для определения. Silent и Balanced различает только байт 0xD4 (1D = Silent)." },
        ["fc_silent_warn"] = new[] {
            "Silent's power cap lives in the same byte as the fan curve (0xD4), so a custom curve turns Silent off — the laptop runs at Balanced power with your fans. Continue?",
            "Limit mocy Silenta siedzi w tym samym bajcie co krzywa (0xD4), więc własna krzywa wyłącza Silent — laptop pójdzie na mocy Balanced z Twoimi wentylatorami. Kontynuować?",
            "Das Power-Limit von Silent liegt im selben Byte wie die Kurve (0xD4) — eine eigene Kurve schaltet Silent ab; der Laptop läuft mit Balanced-Leistung. Fortfahren?",
            "Le plafond de puissance Silent est dans le même octet que la courbe (0xD4) ; une courbe désactive Silent — puissance Balanced avec vos ventilateurs. Continuer ?",
            "El límite de potencia de Silent está en el mismo byte que la curva (0xD4); una curva desactiva Silent — potencia Balanced con tus ventiladores. ¿Continuar?",
            "Silent 的功耗上限与风扇曲线在同一字节（0xD4），自定义曲线会关闭 Silent——将以 Balanced 功耗运行。继续？",
            "O limite de potência do Silent está no mesmo byte da curva (0xD4); uma curva desliga o Silent — potência Balanced com suas ventoinhas. Continuar?",
            "Лимит мощности Silent в том же байте, что и кривая (0xD4); своя кривая отключает Silent — ноутбук работает на мощности Balanced. Продолжить?" },
        ["fc_mode"]        = new[] { "Fan mode:", "Tryb wentylatora:", "Lüftermodus:", "Mode ventilateur :", "Modo ventilador:", "风扇模式：", "Modo da ventoinha:", "Режим вентилятора:" },
        ["fc_default"]     = new[] { "MSI default", "MSI domyślny", "MSI-Standard", "MSI par défaut", "MSI predeterminado", "MSI 默认", "Padrão MSI", "По умолчанию MSI" },
        ["fc_applied"]     = new[] { "Custom fan curve applied to the current mode.", "Własna krzywa zastosowana w aktualnym trybie.", "Eigene Lüfterkurve im aktuellen Modus angewendet.", "Courbe personnalisée appliquée au mode actuel.", "Curva personalizada aplicada al modo actual.", "已在当前模式应用自定义曲线。", "Curva personalizada aplicada ao modo atual.", "Своя кривая применена в текущем режиме." },
        ["fc_warn_low"]    = new[] {
            "The highest-temperature speed is low — fans may stay quiet under heavy load and the laptop can get hot. Apply anyway?",
            "Prędkość przy najwyższej temperaturze jest niska — pod dużym obciążeniem wentylatory mogą zostać ciche i laptop się zagrzeje. Zastosować mimo to?",
            "Die Drehzahl bei höchster Temperatur ist niedrig — unter Last können die Lüfter leise bleiben und das Gerät heiß werden. Trotzdem anwenden?",
            "La vitesse à la température max est faible — sous charge, les ventilateurs peuvent rester silencieux et le PC chauffer. Appliquer quand même ?",
            "La velocidad a la temperatura máxima es baja — con carga, los ventiladores pueden quedar silenciosos y el equipo calentarse. ¿Aplicar igual?",
            "最高温度下的转速偏低——重载时风扇可能仍很安静、机器会发热。仍要应用吗？",
            "A velocidade na temperatura máxima é baixa — sob carga, as ventoinhas podem ficar silenciosas e o aparelho esquentar. Aplicar mesmo assim?",
            "Скорость при макс. температуре низкая — под нагрузкой вентиляторы могут остаться тихими, и ноутбук нагреется. Всё равно применить?" },
        ["test_curve_btn"] = new[] { "Show fan curve (read-only)", "Pokaż krzywą wentylatora (read-only)", "Lüfterkurve anzeigen (nur Lesen)", "Afficher la courbe (lecture seule)", "Mostrar curva (solo lectura)", "显示风扇曲线（只读）", "Mostrar curva (somente leitura)", "Показать кривую (только чтение)" },
        ["test_curve_none"]= new[] { "No fan-curve map for this model yet.", "Brak mapy krzywej dla tego modelu.", "Noch keine Lüfterkurven-Map für dieses Modell.", "Pas encore de courbe pour ce modèle.", "Aún no hay mapa de curva para este modelo.", "该型号尚无风扇曲线映射。", "Ainda não há mapa de curva para este modelo.", "Для этой модели пока нет карты кривой." },
        ["test_curve_hint"]= new[] {
            "Read-only preview — compare with MSI Center (Extreme → Advanced) to confirm the point count and values.",
            "Podgląd tylko do odczytu — porównaj z MSI Center (Extreme → Advanced), aby potwierdzić liczbę punktów i wartości.",
            "Nur-Lese-Vorschau — mit MSI Center (Extreme → Advanced) vergleichen, um Punktanzahl und Werte zu bestätigen.",
            "Aperçu en lecture seule — comparez avec MSI Center (Extreme → Advanced) pour confirmer le nombre de points et les valeurs.",
            "Vista previa de solo lectura — compara con MSI Center (Extreme → Advanced) para confirmar el número de puntos y los valores.",
            "只读预览——与 MSI Center（Extreme → Advanced）对比以确认点数和数值。",
            "Pré-visualização somente leitura — compare com o MSI Center (Extreme → Advanced) para confirmar o número de pontos e valores.",
            "Предпросмотр только для чтения — сравните с MSI Center (Extreme → Advanced), чтобы подтвердить число точек и значения." },
        ["test_dump_saved"]= new[] { "Saved to:\n{0}", "Zapisano do:\n{0}", "Gespeichert:\n{0}", "Enregistré :\n{0}", "Guardado en:\n{0}", "已保存到：\n{0}", "Salvo em:\n{0}", "Сохранено:\n{0}" },
        ["test_adv_on"]    = new[] { "Silent + Advanced fan (0xD4=0x8D)", "Silent + Advanced (0xD4=0x8D)", "Silent + Advanced (0xD4=0x8D)", "Silent + Advanced (0xD4=0x8D)", "Silent + Advanced (0xD4=0x8D)", "Silent + 高级 (0xD4=0x8D)", "Silent + Advanced (0xD4=0x8D)", "Silent + Advanced (0xD4=0x8D)" },
        ["test_adv_off"]   = new[] { "Restore Silent", "Przywróć Silent", "Silent wiederherstellen", "Restaurer Silent", "Restaurar Silent", "恢复 Silent", "Restaurar Silent", "Вернуть Silent" },
        ["test_note"]      = new[] {
            "Experiment: does the EC obey advanced fan control outside Extreme? Apply, watch the fans, then restore. Tested models only.",
            "Eksperyment: czy EC słucha trybu Advanced poza Extreme? Włącz, obserwuj wentylatory, potem przywróć. Tylko modele Tested.",
            "Experiment: gehorcht der EC dem Advanced-Modus außerhalb Extreme? Anwenden, Lüfter beobachten, dann zurücksetzen. Nur getestete Modelle.",
            "Expérience : l'EC obéit-il au mode Advanced hors Extreme ? Appliquez, observez les ventilateurs, puis restaurez. Modèles testés uniquement.",
            "Experimento: ¿obedece el EC el modo Advanced fuera de Extreme? Aplica, observa los ventiladores y restaura. Solo modelos probados.",
            "实验：在 Extreme 之外 EC 是否服从高级风扇控制？应用、观察风扇，然后恢复。仅限已测试机型。",
            "Experimento: o EC obedece ao modo Advanced fora do Extreme? Aplique, observe as ventoinhas e restaure. Apenas modelos testados.",
            "Эксперимент: слушается ли EC режима Advanced вне Extreme? Примените, посмотрите на вентиляторы, затем верните. Только проверенные модели." },
        ["tab_report"]     = new[] { "Report", "Zgłoś", "Melden", "Signaler", "Reportar", "提交机型", "Reportar", "Сообщить" },
        // ---- Models tab (EN + PL; other languages fall back to EN) ----
        ["tab_models"]     = new[] { "Models", "Modele" },
        ["mdl_intro"]      = new[] {
            "Every firmware ID the app recognises: 1 tested on real hardware, the rest experimental (opt-in) from the msi-ec / MControlCenter register maps. On an unrecognised firmware the app stays read-only.",
            "Wszystkie identyfikatory firmware rozpoznawane przez aplikację: 1 zweryfikowany na sprzęcie, reszta eksperymentalna (opcjonalna) z map rejestrów msi-ec / MControlCenter. Nieznany firmware = tryb tylko do odczytu." },
        ["mdl_you"]        = new[] { "Your model", "Twój model" },
        ["mdl_unknown"]    = new[] { "Firmware {0} not recognised — read-only mode.", "Firmware {0} nierozpoznany — tryb tylko do odczytu." },
        ["mdl_c_family"]   = new[] { "Family", "Rodzina" },
        ["mdl_c_status"]   = new[] { "Status", "Status" },
        ["mdl_c_curve"]    = new[] { "Fan curve", "Krzywa" },
        ["mdl_c_sb"]       = new[] { "SB", "SB" },
        ["mdl_c_rpm"]      = new[] { "RPM", "RPM" },
        ["mdl_curve_edit"] = new[] { "editable", "edytowalna" },
        ["mdl_curve_prev"] = new[] { "unverified", "niezweryfikowany" },
        ["mdl_sb_tip"]     = new[] {
            "Super Battery\nWhether the model has a dedicated super-battery\nregister (deepest power/battery throttle).\nAffects the Super Battery profile.",
            "Super Battery\nCzy model ma dedykowany rejestr super-baterii\n(najgłębszy throttle mocy/baterii).\nWpływa na profil Super Battery." },
        ["mdl_search"]     = new[] { "Search model or firmware…", "Szukaj modelu lub firmware…" },
        ["mdl_legend"]     = new[] {
            "Fan curve:  ✓ editable = writable now   ·   ◉ unverified = editable after enabling Experimental, but addresses unconfirmed - compare with MSI Center first   ·   — = none.   SB = has a super-battery register.   RPM = fan-tachometer address known (real RPM shown).",
            "Krzywa:  ✓ edytowalna = zapisywalna od razu   ·   ◉ niezweryfikowany = edytowalna po włączeniu trybu eksperymentalnego, ale adresy niepotwierdzone - najpierw porównaj z MSI Center   ·   — = brak.   SB = ma rejestr super-baterii.   RPM = znany adres tachometru (pokazuje realne RPM)." },
        ["set_grp_look"]   = new[] { "Appearance", "Wygląd", "Darstellung", "Apparence", "Apariencia", "外观", "Aparência", "Вид" },
        ["set_grp_power"]  = new[] { "Power", "Zasilanie", "Energie", "Alimentation", "Energía", "电源", "Energia", "Питание" },
        ["set_grp_start"]  = new[] { "Startup & tray", "Start i zasobnik", "Start & Infobereich", "Démarrage", "Inicio", "启动与托盘", "Inicialização", "Запуск" },
        ["set_grp_updates"]= new[] { "Updates", "Aktualizacje", "Updates", "Mises à jour", "Actualizaciones", "更新", "Atualizações", "Обновления" },
        ["set_grp_tray"]   = new[] { "Tray menu", "Menu w zasobniku", "Infobereichsmenü", "Menu de la barre d'état", "Menú de bandeja", "托盘菜单", "Menu da bandeja", "Меню в трее" },
        ["rep_step"]       = new[] { "Step {0} of {1}", "Krok {0} z {1}", "Schritt {0} von {1}", "Étape {0} sur {1}", "Paso {0} de {1}", "第 {0} / {1} 步", "Etapa {0} de {1}", "Шаг {0} из {1}" },
        ["rep_set_scenario"] = new[] {
            "In MSI Center set the scenario to: {0}, then click Capture.",
            "W MSI Center ustaw scenariusz: {0}, następnie kliknij Przechwyć.",
            "Im MSI Center das Szenario auf {0} setzen, dann Erfassen klicken.",
            "Dans MSI Center, réglez le scénario sur : {0}, puis cliquez sur Capturer.",
            "En MSI Center fija el escenario en: {0}, luego pulsa Capturar.",
            "在 MSI Center 中将场景设为：{0}，然后点击采集。",
            "No MSI Center defina o cenário como: {0}, depois clique em Capturar.",
            "В MSI Center установите сценарий: {0}, затем нажмите «Снять»." },
        ["rep_capture"]    = new[] { "Capture", "Przechwyć", "Erfassen", "Capturer", "Capturar", "采集", "Capturar", "Снять" },
        ["rep_capturing"]  = new[] { "Reading EC…", "Odczyt EC…", "EC wird gelesen…", "Lecture de l'EC…", "Leyendo EC…", "正在读取 EC…", "Lendo EC…", "Чтение EC…" },
        ["rep_captured"]   = new[] { "captured", "przechwycono", "erfasst", "capturé", "capturado", "已采集", "capturado", "снято" },
        ["rep_pending"]    = new[] { "pending", "oczekuje", "ausstehend", "en attente", "pendiente", "待采集", "pendente", "ожидание" },
        ["rep_all_done"]   = new[] {
            "All scenarios captured. The report was copied to your clipboard and saved to a file. Click Finish to open the GitHub form — paste the full report (Ctrl+V) into the \"Full EC dump per scenario (optional, very helpful)\" field.",
            "Wszystkie scenariusze przechwycone. Raport skopiowano do schowka i zapisano do pliku. Kliknij Zakończ, aby otworzyć formularz GitHub — wklej pełny raport (Ctrl+V) w pole \"Full EC dump per scenario (optional, very helpful)\".",
            "Alle Szenarien erfasst. Der Bericht wurde in die Zwischenablage kopiert und als Datei gespeichert. Auf Fertig klicken, um das GitHub-Formular zu öffnen — vollständigen Bericht (Strg+V) in das Feld \"Full EC dump per scenario (optional, very helpful)\" einfügen.",
            "Tous les scénarios capturés. Le rapport a été copié dans le presse-papiers et enregistré. Cliquez sur Terminer pour ouvrir le formulaire GitHub — collez le rapport complet (Ctrl+V) dans le champ \"Full EC dump per scenario (optional, very helpful)\".",
            "Todos los escenarios capturados. El informe se copió al portapapeles y se guardó en un archivo. Pulsa Finalizar para abrir el formulario de GitHub — pega el informe completo (Ctrl+V) en el campo \"Full EC dump per scenario (optional, very helpful)\".",
            "已采集所有场景。报告已复制到剪贴板并保存为文件。点击完成以打开 GitHub 表单——将完整报告（Ctrl+V）粘贴到 \"Full EC dump per scenario (optional, very helpful)\" 字段。",
            "Todos os cenários capturados. O relatório foi copiado para a área de transferência e salvo em arquivo. Clique em Concluir para abrir o formulário do GitHub — cole o relatório completo (Ctrl+V) no campo \"Full EC dump per scenario (optional, very helpful)\".",
            "Все сценарии сняты. Отчёт скопирован в буфер обмена и сохранён в файл. Нажмите «Готово», чтобы открыть форму GitHub — вставьте полный отчёт (Ctrl+V) в поле \"Full EC dump per scenario (optional, very helpful)\"." },
        ["rep_finish"]     = new[] { "Finish & open GitHub", "Zakończ i otwórz GitHub", "Fertig & GitHub öffnen", "Terminer & ouvrir GitHub", "Finalizar y abrir GitHub", "完成并打开 GitHub", "Concluir e abrir GitHub", "Готово и открыть GitHub" },
        ["rep_cancel"]     = new[] { "Cancel", "Anuluj", "Abbrechen", "Annuler", "Cancelar", "取消", "Cancelar", "Отмена" },
        ["rep_saved_to"]   = new[] { "Saved to: {0}", "Zapisano do: {0}", "Gespeichert unter: {0}", "Enregistré dans : {0}", "Guardado en: {0}", "已保存到：{0}", "Salvo em: {0}", "Сохранено в: {0}" },
        ["rep_read_fail"]  = new[] {
            "Couldn't read the EC (is the MSI WMI interface available?). Details: {0}",
            "Nie udało się odczytać EC (czy interfejs WMI MSI jest dostępny?). Szczegóły: {0}",
            "EC konnte nicht gelesen werden (ist die MSI-WMI-Schnittstelle verfügbar?). Details: {0}",
            "Impossible de lire l'EC (l'interface WMI MSI est-elle disponible ?). Détails : {0}",
            "No se pudo leer el EC (¿está disponible la interfaz WMI de MSI?). Detalles: {0}",
            "无法读取 EC（MSI WMI 接口是否可用？）。详情：{0}",
            "Não foi possível ler o EC (a interface WMI da MSI está disponível?). Detalhes: {0}",
            "Не удалось прочитать EC (доступен ли интерфейс MSI WMI?). Подробности: {0}" },

        ["yes"]            = new[] { "Yes", "Tak", "Ja", "Oui", "Sí", "是", "Sim", "Да" },
        ["no"]             = new[] { "No", "Nie", "Nein", "Non", "No", "否", "Não", "Нет" },
        ["err"]            = new[] { "ERROR", "BŁĄD", "FEHLER", "ERREUR", "ERROR", "错误", "ERRO", "ОШИБКА" },

        ["sub_silent"]       = new[] { "quiet · ~30–40 W", "cicho · ~30–40 W", "leise · ~30–40 W", "silencieux · ~30–40 W", "silencioso · ~30–40 W", "安静 · ~30–40 W", "silencioso · ~30–40 W", "тихо · ~30–40 W" },
        ["sub_balanced"]     = new[] { "full power", "pełna moc", "volle Leistung", "pleine puissance", "máxima potencia", "全功率", "potência total", "полная мощность" },
        ["sub_extreme"]      = new[] { "max · loud", "maks · głośno", "max · laut", "max · bruyant", "máx · ruidoso", "最大 · 吵", "máx · ruidoso", "макс · громко" },
        ["sub_superbattery"] = new[] { "saving · ~15 W", "oszczędzanie · ~15 W", "sparen · ~15 W", "économie · ~15 W", "ahorro · ~15 W", "省电 · ~15 W", "economia · ~15 W", "экономия · ~15 W" },
    };
}
