using System.Net.Http;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

namespace GhostDeck;

/// <summary>
/// Signed, separately-updatable model database. The SOURCE OF TRUTH stays `Devices.cs`
/// (comments, review flow and the msi-ec sync tool all keep working on it); this class turns
/// those compiled tables into a wire format and back:
///
///  - Dump() serialises the compiled tables to canonical JSON (`data/models.json` in the
///    repo, written via the hidden CLI `--dump-models`). CI regenerates and byte-compares,
///    so the committed file can never drift from the code, and Parse(Dump()) round-trips.
///  - The file is SIGNED (ECDSA P-256 / SHA-256, detached `models.json.sig`); only the
///    private key held OFFLINE by the maintainer can produce updates. The public key below
///    is the only trust anchor the app has - an unsigned or tampered file is ignored.
///  - At startup LoadOverride() checks %AppData%\GhostDeck\models.json: signature verified
///    on EVERY load (a file can be tampered with long after download), then dataVersion
///    must be NEWER than the compiled tables (anti-rollback), then sanity validation -
///    this data drives EC writes. Any failure = silent fallback to the compiled tables
///    plus an errors.log line; the app never breaks because of a bad download.
///  - The daily update check fetches data/models.json(.sig) from the repo (raw bytes -
///    see .gitattributes: the file is marked -text so the served blob is byte-identical
///    to what was signed) and stores it; it takes effect on the next start.
///
/// MSIPS_MODELS_JSON=&lt;path&gt; loads an UNSIGNED local file instead (explicit, this-machine
/// testing hook, same spirit as MSIPS_FORCE_FIRMWARE).
/// </summary>
public static class ModelDb
{
    public const int SchemaVersion = 1;

    // ECDSA P-256 public key (SubjectPublicKeyInfo, base64). The private key is generated by
    // tools/gen-model-key.ps1 OUTSIDE the repo and never leaves the maintainer's machine.
    // Also committed as tools/model-signing.pub for the CI signature check.
    private const string PublicKeySpki = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE+2Rv1LmyCZwigqdVi9kiCRSiCUuHGFd8Wg0kJVN4Xt2Uy0AzAeRxlxYwk6Qve8Mx4uiEYYHoLykJKPh9UCYp/w==";

    public sealed record Parsed(
        int DataVersion,
        DeviceProfile[] Models,
        Dictionary<string, byte> KbdBacklight,
        HashSet<string> NoWebcamCtrl,
        Dictionary<string, (byte Addr, bool Invert)> FnWinSwap);

    // Field defaults come from a blank DeviceProfile, so dump and parse can never disagree
    // with the class initialisers.
    private static readonly DeviceProfile Def = new()
    {
        Name = "", FirmwarePrefixes = Array.Empty<string>(), Recipes = new(),
    };

    private static string Hex(byte b) => "0x" + b.ToString("X2");

    // ---------------- dump (compiled tables -> canonical JSON bytes) ----------------

    /// <summary>Canonical JSON bytes of the COMPILED tables (data/models.json is exactly this).</summary>
    public static byte[] Dump() =>
        DumpCore(Devices.BuiltIn, Devices.KbdBacklightRef,
                 Devices.NoWebcamCtrlRef, Devices.FnWinSwapRef, Devices.DataVersion);

    /// <summary>Re-serialise a parsed database - byte-equal to its source file (round-trip proof).</summary>
    public static byte[] DumpParsed(Parsed p) =>
        DumpCore(p.Models, p.KbdBacklight, p.NoWebcamCtrl, p.FnWinSwap, p.DataVersion);

    private static byte[] DumpCore(
        IReadOnlyList<DeviceProfile> models,
        IReadOnlyDictionary<string, byte> kbd,
        IReadOnlyCollection<string> noCam,
        IReadOnlyDictionary<string, (byte Addr, bool Invert)> fnSwap,
        int dataVersion)
    {
        using var ms = new MemoryStream();
        using (var w = new Utf8JsonWriter(ms, new JsonWriterOptions { Indented = true }))
        {
            w.WriteStartObject();
            w.WriteNumber("schemaVersion", SchemaVersion);
            w.WriteNumber("dataVersion", dataVersion);
            w.WriteStartArray("models");
            foreach (var d in models) WriteModel(w, d);
            w.WriteEndArray();
            w.WriteStartObject("maps");
            w.WriteStartObject("kbdBacklight");
            foreach (var (k, v) in kbd.OrderBy(p => p.Key, StringComparer.Ordinal))
                w.WriteString(k, Hex(v));
            w.WriteEndObject();
            w.WriteStartArray("noWebcamCtrl");
            foreach (var p in noCam.OrderBy(x => x, StringComparer.Ordinal))
                w.WriteStringValue(p);
            w.WriteEndArray();
            w.WriteStartObject("fnWinSwap");
            foreach (var (k, v) in fnSwap.OrderBy(p => p.Key, StringComparer.Ordinal))
            {
                w.WriteStartObject(k);
                w.WriteString("addr", Hex(v.Addr));
                w.WriteBoolean("invert", v.Invert);
                w.WriteEndObject();
            }
            w.WriteEndObject();
            w.WriteEndObject();
            w.WriteEndObject();
        }
        return ms.ToArray();
    }

    private static void WriteModel(Utf8JsonWriter w, DeviceProfile d)
    {
        w.WriteStartObject();
        w.WriteString("name", d.Name);
        w.WriteStartArray("prefixes");
        foreach (var p in d.FirmwarePrefixes) w.WriteStringValue(p);
        w.WriteEndArray();
        w.WriteString("tier", d.Tier.ToString());
        // register overrides only when they differ from the class defaults (G2 layout)
        if (d.ShiftMode != Def.ShiftMode) w.WriteString("shiftMode", Hex(d.ShiftMode));
        if (d.FanMode != Def.FanMode) w.WriteString("fanMode", Hex(d.FanMode));
        if (d.CpuTemp != Def.CpuTemp) w.WriteString("cpuTemp", Hex(d.CpuTemp));
        if (d.GpuTemp != Def.GpuTemp) w.WriteString("gpuTemp", Hex(d.GpuTemp));
        if (d.CpuFan != Def.CpuFan) w.WriteString("cpuFan", Hex(d.CpuFan));
        if (d.GpuFan != Def.GpuFan) w.WriteString("gpuFan", Hex(d.GpuFan));
        if (d.ChargeCtrl != Def.ChargeCtrl) w.WriteString("chargeCtrl", Hex(d.ChargeCtrl));
        if (d.CoolerBoost != Def.CoolerBoost) w.WriteString("coolerBoost", Hex(d.CoolerBoost));
        if (d.CoolerBoostMask != Def.CoolerBoostMask) w.WriteString("coolerBoostMask", Hex(d.CoolerBoostMask));
        if (d.CpuRpmAddr != 0) w.WriteString("cpuRpmAddr", Hex(d.CpuRpmAddr));
        if (d.GpuRpmAddr != 0) w.WriteString("gpuRpmAddr", Hex(d.GpuRpmAddr));
        if (d.RpmConst != Def.RpmConst) w.WriteNumber("rpmConst", d.RpmConst);
        if (d.FanSilentValue != Def.FanSilentValue) w.WriteString("fanSilentValue", Hex(d.FanSilentValue));
        if (d.ShiftTurboValue != Def.ShiftTurboValue) w.WriteString("shiftTurboValue", Hex(d.ShiftTurboValue));
        if (d.ShiftEcoValue != Def.ShiftEcoValue) w.WriteString("shiftEcoValue", Hex(d.ShiftEcoValue));
        if (d.FanCurve is { } fc)
        {
            w.WriteStartObject("fanCurve");
            w.WriteString("advancedModeValue", Hex(fc.AdvancedModeValue));
            w.WriteString("cpuTempBase", Hex(fc.CpuTempBase));
            w.WriteString("cpuSpeedBase", Hex(fc.CpuSpeedBase));
            w.WriteString("gpuTempBase", Hex(fc.GpuTempBase));
            w.WriteString("gpuSpeedBase", Hex(fc.GpuSpeedBase));
            w.WriteNumber("points", fc.Points);
            w.WriteBoolean("verified", fc.Verified);
            w.WriteBoolean("singleFan", fc.SingleFan);
            w.WriteEndObject();
        }
        if (d.Credit.Length > 0) w.WriteString("credit", d.Credit);
        if (d.CreditUrl.Length > 0) w.WriteString("creditUrl", d.CreditUrl);
        // recipes always explicit ("0xAA=0xVV" pairs) - the file is generated, never hand-edited
        w.WriteStartObject("recipes");
        foreach (var id in Profiles.Order)
        {
            w.WriteStartArray(id.ToString());
            foreach (var (a, v) in d.Recipes[id]) w.WriteStringValue($"{Hex(a)}={Hex(v)}");
            w.WriteEndArray();
        }
        w.WriteEndObject();
        w.WriteEndObject();
    }

    // ---------------- parse (JSON bytes -> tables) ----------------

    public static bool TryParse(byte[] data, out Parsed? parsed, out string error)
    {
        parsed = null;
        try
        {
            using var doc = JsonDocument.Parse(data);
            var root = doc.RootElement;
            if (root.GetProperty("schemaVersion").GetInt32() != SchemaVersion) { error = "unknown schemaVersion"; return false; }
            int dataVersion = root.GetProperty("dataVersion").GetInt32();

            var models = new List<DeviceProfile>();
            foreach (var m in root.GetProperty("models").EnumerateArray())
                models.Add(ParseModel(m));

            var kbd = new Dictionary<string, byte>(StringComparer.OrdinalIgnoreCase);
            var noCam = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            var fnSwap = new Dictionary<string, (byte, bool)>(StringComparer.OrdinalIgnoreCase);
            var maps = root.GetProperty("maps");
            foreach (var p in maps.GetProperty("kbdBacklight").EnumerateObject())
                kbd[p.Name] = ParseByte(p.Value.GetString());
            foreach (var e in maps.GetProperty("noWebcamCtrl").EnumerateArray())
                noCam.Add(e.GetString() ?? "");
            foreach (var p in maps.GetProperty("fnWinSwap").EnumerateObject())
                fnSwap[p.Name] = (ParseByte(p.Value.GetProperty("addr").GetString()),
                                  p.Value.GetProperty("invert").GetBoolean());

            var result = new Parsed(dataVersion, models.ToArray(), kbd, noCam, fnSwap);
            if (!Validate(result, out error)) return false;
            parsed = result;
            error = "";
            return true;
        }
        catch (Exception ex)
        {
            error = ex.Message;
            return false;
        }
    }

    private static DeviceProfile ParseModel(JsonElement m)
    {
        byte B(string name, byte def) => m.TryGetProperty(name, out var v) ? ParseByte(v.GetString()) : def;
        var recipes = new Dictionary<ProfileId, (byte, byte)[]>();
        foreach (var p in m.GetProperty("recipes").EnumerateObject())
        {
            var list = new List<(byte, byte)>();
            foreach (var e in p.Value.EnumerateArray())
            {
                var parts = (e.GetString() ?? "").Split('=');
                list.Add((ParseByte(parts[0]), ParseByte(parts[1])));
            }
            recipes[Enum.Parse<ProfileId>(p.Name)] = list.ToArray();
        }
        FanCurveSpec? curve = null;
        if (m.TryGetProperty("fanCurve", out var fc))
            curve = new FanCurveSpec(
                ParseByte(fc.GetProperty("advancedModeValue").GetString()),
                ParseByte(fc.GetProperty("cpuTempBase").GetString()),
                ParseByte(fc.GetProperty("cpuSpeedBase").GetString()),
                ParseByte(fc.GetProperty("gpuTempBase").GetString()),
                ParseByte(fc.GetProperty("gpuSpeedBase").GetString()),
                fc.GetProperty("points").GetInt32(),
                fc.GetProperty("verified").GetBoolean(),
                fc.GetProperty("singleFan").GetBoolean());
        return new DeviceProfile
        {
            Name = m.GetProperty("name").GetString() ?? "",
            FirmwarePrefixes = m.GetProperty("prefixes").EnumerateArray().Select(e => e.GetString() ?? "").ToArray(),
            Tier = Enum.Parse<Tier>(m.GetProperty("tier").GetString() ?? "Experimental"),
            ShiftMode = B("shiftMode", Def.ShiftMode),
            FanMode = B("fanMode", Def.FanMode),
            CpuTemp = B("cpuTemp", Def.CpuTemp),
            GpuTemp = B("gpuTemp", Def.GpuTemp),
            CpuFan = B("cpuFan", Def.CpuFan),
            GpuFan = B("gpuFan", Def.GpuFan),
            ChargeCtrl = B("chargeCtrl", Def.ChargeCtrl),
            CoolerBoost = B("coolerBoost", Def.CoolerBoost),
            CoolerBoostMask = B("coolerBoostMask", Def.CoolerBoostMask),
            CpuRpmAddr = B("cpuRpmAddr", 0),
            GpuRpmAddr = B("gpuRpmAddr", 0),
            RpmConst = m.TryGetProperty("rpmConst", out var rc) ? rc.GetInt32() : Def.RpmConst,
            FanSilentValue = B("fanSilentValue", Def.FanSilentValue),
            ShiftTurboValue = B("shiftTurboValue", Def.ShiftTurboValue),
            ShiftEcoValue = B("shiftEcoValue", Def.ShiftEcoValue),
            FanCurve = curve,
            Credit = m.TryGetProperty("credit", out var cr) ? cr.GetString() ?? "" : "",
            CreditUrl = m.TryGetProperty("creditUrl", out var cu) ? cu.GetString() ?? "" : "",
            Recipes = recipes,
        };
    }

    private static byte ParseByte(string? s)
    {
        s = s?.Trim() ?? throw new FormatException("null byte value");
        return s.StartsWith("0x", StringComparison.OrdinalIgnoreCase)
            ? Convert.ToByte(s[2..], 16)
            : byte.Parse(s);
    }

    // Sanity: this data drives EC writes, so a structurally valid but nonsensical file is
    // rejected the same way a bad signature is.
    private static bool Validate(Parsed p, out string error)
    {
        error = "";
        if (p.Models.Length == 0) { error = "no models"; return false; }
        var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var d in p.Models)
        {
            if (string.IsNullOrWhiteSpace(d.Name)) { error = "model without a name"; return false; }
            if (d.FirmwarePrefixes.Length == 0) { error = d.Name + ": no prefixes"; return false; }
            foreach (var pf in d.FirmwarePrefixes)
                if (pf.Length is < 4 or > 12 || !seen.Add(pf)) { error = d.Name + ": bad/duplicate prefix " + pf; return false; }
            foreach (var id in Profiles.Order)
                if (!d.Recipes.TryGetValue(id, out var r) || r.Length == 0) { error = d.Name + ": missing recipe " + id; return false; }
            if (d.FanCurve is { } fc && fc.Points is < 1 or > 16) { error = d.Name + ": bad curve points"; return false; }
        }
        return true;
    }

    // ---------------- signature ----------------

    public static bool VerifySignature(byte[] data, string signatureBase64)
    {
        try
        {
            using var ecdsa = ECDsa.Create();
            ecdsa.ImportSubjectPublicKeyInfo(Convert.FromBase64String(PublicKeySpki), out _);
            return ecdsa.VerifyData(data, Convert.FromBase64String(signatureBase64.Trim()),
                HashAlgorithmName.SHA256, DSASignatureFormat.Rfc3279DerSequence);
        }
        catch { return false; }
    }

    // ---------------- load / update ----------------

    private static string CachePath => Path.Combine(AppSettings.Dir, "models.json");
    private static string CacheSigPath => Path.Combine(AppSettings.Dir, "models.json.sig");

    /// <summary>Downloaded-and-valid-and-newer database, or null = stay on the compiled tables.</summary>
    public static Parsed? LoadOverride()
    {
        // explicit local testing hook - unsigned, no version gate, this machine only
        var env = Environment.GetEnvironmentVariable("MSIPS_MODELS_JSON");
        if (!string.IsNullOrEmpty(env) && File.Exists(env))
        {
            if (TryParse(File.ReadAllBytes(env), out var p, out var err) && p != null) return p;
            AppLifecycle.Report(new InvalidDataException(err), "model-db env override");
            return null;
        }
        try
        {
            if (!File.Exists(CachePath) || !File.Exists(CacheSigPath)) return null;
            byte[] data = File.ReadAllBytes(CachePath);
            if (!VerifySignature(data, File.ReadAllText(CacheSigPath)))
            {
                AppLifecycle.Report(new InvalidDataException("cached models.json failed the signature check"), "model-db");
                return null;
            }
            if (!TryParse(data, out var parsed, out string error) || parsed == null)
            {
                AppLifecycle.Report(new InvalidDataException(error), "model-db");
                return null;
            }
            return parsed.DataVersion > Devices.DataVersion ? parsed : null;   // anti-rollback
        }
        catch (Exception ex)
        {
            AppLifecycle.Report(ex, "model-db load");
            return null;
        }
    }

    /// <summary>Version waiting in the cache for the next start, or null (for the Settings row).</summary>
    public static int? PendingVersion()
    {
        try
        {
            if (!File.Exists(CachePath) || !File.Exists(CacheSigPath)) return null;
            byte[] data = File.ReadAllBytes(CachePath);
            if (!VerifySignature(data, File.ReadAllText(CacheSigPath))) return null;
            if (!TryParse(data, out var p, out _) || p == null) return null;
            return p.DataVersion > Devices.EffectiveDataVersion ? p.DataVersion : null;
        }
        catch { return null; }
    }

    private const string BaseUrl = "https://raw.githubusercontent.com/wygodad/ghostdeck/main/data/";

    /// <summary>
    /// Fetch the published database (same cadence and privacy footprint as the update check);
    /// a valid, newer file is stored and applies on the next start. Returns its dataVersion
    /// when something new was stored, else null. All failures are silent (offline is normal).
    /// </summary>
    public static async Task<int?> FetchUpdateAsync()
    {
        try
        {
            using var http = new HttpClient { Timeout = TimeSpan.FromSeconds(15) };
            http.DefaultRequestHeaders.UserAgent.ParseAdd("GhostDeck-ModelDb");
            byte[] data = await http.GetByteArrayAsync(BaseUrl + "models.json").ConfigureAwait(false);
            string sig = await http.GetStringAsync(BaseUrl + "models.json.sig").ConfigureAwait(false);
            if (!VerifySignature(data, sig)) return null;
            if (!TryParse(data, out var parsed, out _) || parsed == null) return null;
            int have = Math.Max(Devices.EffectiveDataVersion, PendingVersion() ?? 0);
            if (parsed.DataVersion <= have) return null;
            File.WriteAllBytes(CachePath, data);
            File.WriteAllText(CacheSigPath, sig.Trim());
            return parsed.DataVersion;
        }
        catch { return null; }
    }
}
